apiVersion: v1
kind: Secret
metadata:
    name: hermes-agent-secret
stringData:
    #ENC[AES256_GCM,data:9jxHqBWj5w2GxLbGd+AgKvUi0YIGMCdt3x1zusVuRVr1ZEUtmA7gQQlTcZFf3iIsK6ELha1r8xs0qAGEfaSnW80X1BgdfiA=,iv:W49u7V4W2Dwcc5qWbN5KatAMywoX6WlC8AJOV+E7MzQ=,tag:SYA8E1d8SHPoxeyE0tSlkA==,type:comment]
    SLACK_BOT_TOKEN: ENC[AES256_GCM,data:HT9667zxyFNnyL0vqAvxeu/ui1KdK5h2qVRrn5Dx1ZwIpI0Asqzye6QoOwSize2uMA73D5aiQOVpRA==,iv:OCK79VJzTT4nboW3pqslpibVSDPfcAZP3hs1sW0At1Y=,tag:wO5+D/1plYbgItiiWTw6bw==,type:str]
    #ENC[AES256_GCM,data:zt9oqhOgpIc3uvLnc2kvfKyJUEw9YLK8F3txLkpx4i3TY5hpMJonCgu9gtwOCaH1XSkUr6pMksyDv91D0s3reDI=,iv:s1GMN8O/uQz7ydWbukgeICjsGsZ3Xa+laCF4HuON/rE=,tag:1xh8xMWGAY5596a3oqs9og==,type:comment]
    SLACK_APP_TOKEN: ENC[AES256_GCM,data:cL6CLXhfiml4LJ2TlsQLbpoj72RaRifV+T1vR3yRa69Ms14RlrQF0vT8e44SoDOfizQleHLTD+93CTFaqcuI+1sshI0q+W7pXHqKI46IbhbAGr8zgi3WIbnKTerOXTTq+M0=,iv:cQSQ48aZ698bv6F940T76BDgRAlpIv+EbweQpwx3gQ0=,tag:BL7vFwd1UHEOOvYiwA46Vw==,type:str]
    #ENC[AES256_GCM,data:yEMaGl0/1GBEp+VT1zh6h8TQ+j/SGHQNCpVd86FW0T4wsOe4oNS9Prn9PqxCD04sqlKRRNQ4/Aun16oMx5XRVvPvOU5j14w7Muc=,iv:gQ2N4gNffCD+YiJaqmlX4SgoACi8aOCB3v4GhFNEEaw=,tag:cnV77uxqZOw+P0fzmj+iGQ==,type:comment]
    SLACK_ALLOWED_USERS: ENC[AES256_GCM,data:uVrNBNChht/imVs=,iv:3lbblQgLJ+j6F3lnTh4olqY/oLrSwykoqav1AhBG4S4=,tag:6UIjo2qypm7mYXgz2Dlmhw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZFJVak9FQTVMYnhleUky
            TzByMmFScFBMNWxWa3lONTVmbXkzMWpYdWhzCjZVN3dmNXJ2YnZ5Snc3YWMrdjk5
            TGNkdTBDbE54YVpMRkZCWjNuUlBGZFkKLS0tIEpiUVpWaXBxWVMyOXZnTjByRUVq
            SGw5alVmM01TZXZXYnY1VmJaVndWc0UKhqOgtzeEcQSXP/+krdQv+EjPQCmUkmCB
            tcESbSHDUdfaG5acJjGhRXfSfx9XivyeTVCXZbu/lPyKRaXI55zqJA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T21:48:30Z"
    mac: ENC[AES256_GCM,data:ImnQ88cFoGPn3RE6ZhqK253WKqLWbu5BpnZTCxgEsEHbFaKtEYzaZuEmNQuBYYKhjTpKf97d2UdPk1PxRgcyBN8HbXIbXkXBTt8z09IMuAucBHjU39qVDVKPBkp9gr2nKp67uUi1biuTCi//IVpn8jnZ1eZvX+l80vipn4FL6G8=,iv:+TbhU87z2sY/VITS9YTk6aAKoOgPFK/I067WcdFRFfY=,tag:hek+EUTQ2zADxgL7P6OdCg==,type:str]
    version: 3.13.1
