# sops --encrypt --in-place oidc-client-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: echo-oidc-client-secret
stringData:
    #ENC[AES256_GCM,data:EIJJjEAde1V1mVU9fgCN70z6EM1kdGFElgTZYejfiyjVfgbeadjpubJxfD21n5e1QKhi3APMITHDnbYe/ed8HAJohdhI9d2gGxq4+IUjVGB+SQ==,iv:wy5cPrERi6qxizoTKBMJBVaVtkxolPLWbEFpypxo61A=,tag:qkC1UZHpjoPBvnAgW8dUXA==,type:comment]
    #ENC[AES256_GCM,data:/f+4Pfka1NeXVYhDTnGAVTyi/5BFRqa1zEy+RZ1a3J2b91+n3ghFdQrSkQ8VywhGrtMoui+g/mhJ4Rwbo9SPNyvn8xw7EPU=,iv:LPkEmBrp9cKeL1CORO3RLwlX+MVYqOm++dU12FG+CoI=,tag:GzmDmzYpMe0xKtsfoT249w==,type:comment]
    #ENC[AES256_GCM,data:5yyCVsVTMAFvRS+tIBJwq1n7SK11yilgr8gHSIoxOYjkWXrzav5wzrf398r6F/Na2SgHQNJxA4CEmwOhfugiR2UYdK6c24I=,iv:o3IBFnevWJtZOWCF2ilOrnXponreIuq17ReoPZdhglw=,tag:zOUjT226AGOeVTENTO/AkQ==,type:comment]
    #ENC[AES256_GCM,data:mNoafBRh/V3/aWJBZEi37vJpf0rB6oFTVANpJt3i6OpVu4xJ2Prox4kfGDZE3BbmuFJwuwJl3pmq2lKrQKKOaMYTITI=,iv:XGVzjW6mNtFWSzm00X23Cyi4zbfsM8Ab1Yn2uSfnFA0=,tag:YEHIHkMqT8zhsN9A17wAtw==,type:comment]
    #ENC[AES256_GCM,data:9GTP1lXZSYzUw6BXGNYk6iVJwGKexGj7Rchv6YqPH6WL48SCNoKakh2oQqYnYs3UkLPCb9+4I0ryTQUK9DSukw==,iv:2qK2hr9l+bvj70w+AL/yrTMftjRb2TebcQfvB/K6zRQ=,tag:HgpcQOPWUUOxbC9KtoQpwg==,type:comment]
    client-secret: ENC[AES256_GCM,data:v2AXIup6nuMMGmvjx2kJ4+g48QjCCL2hevM3TDuqd6UW/DX2fNRZf3onkQKkHDNiDoB5TMugNEZrkzV+MG2JUsX/l3xe6W7+YpFTJRsSZN0=,iv:44lCHgS6P9RSh+p45aKlBw9+HQk4Z8RRq86skLBFjos=,tag:tmx37jtP4hNJK00v+IVqmg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZkZIUHpralhRZlZvb3Nn
            UnlvbGZZTXZlWjJwWTU4MlBRSHlIL3RmV1dNCllsWkN0YW1QclpTcHRQQ2pMcFNV
            b2RRVDN1blpkRW9hQlN0M1ZWOHU5VlkKLS0tIFk5VDh5QlNoZllMYVBQVnFYWm1w
            eHBuZlM2Z09kSVErb3Rkd1ZiYW9PaUUK1Cf96XLpy98C3LOif20nrxb5Yetnc1KK
            N9T6ypS29avqTfuItkFvhjwrh1b4QHtn3Jau+ezwVMTPsO0CgIbPnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T17:32:17Z"
    mac: ENC[AES256_GCM,data:t+mqPUj7t7uJOVlOVbJpyxIQLdVPuTzrrUyU2XbPgQ5gqfwHMZbdx6DgHLBkrsKkUaSDhCFUwi/PtH6mno9phC09GkOTz9lnGlTvd7HDSyEeJK8cz5+iBJeTmf4XToUlGouJsNV3hJdX6plGloiaO2/3mkCyPSiKDwH/3ZKWGlU=,iv:oflNvd0Nm0w1rtnurx2wAqXPGA+qN8oxOiT1iGcTXbw=,tag:9oztDljoS68d3B7hqGgGzQ==,type:str]
    version: 3.13.1
