apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-config-seed
stringData:
    qBittorrent.conf: ENC[AES256_GCM,data:jKYKq4AL4Kt2u/e1spEskHLb6lVEpxDEuO4ZV3QpIROUP0OmiUvnguTZ+79Hz5nTiCblabo9Z0pctYyJ7zJUvo0tHhqOpIfcvqC8vtkZ7wbYSfufdP1UCv686Xg4ekbxmUe+cUHCmD1HeQuCOdtpiZKVTzjFGeSoHMvTs2ivHOCsvVyTF/cE8utHvAEhPNQiph/Udx99rsk/Lp0nZVvbraJXX2sNX2shNNWvvE5j2pThoNGx6G3HUw6L6k76appYjVIQnrub2h0ldNxgt+tfqKEVXFGzJBZK8tjnPQjEPOwRF+GfixdfvGPmpfWC8YV+CtFWQ8nzLTm30ab8mTt7Pn90dbTrF+CamPFYldQDS7W0W73XIHl+wBx8bvuNwtcL+f5VudlT6IzEmtx5Y5nHvDUuhCjl1XQmyA65Ql1mvdJByvgxLMEIzqxmxQvzs+IeeMsbHC84bNLF/97WR4KVh/9+MYQ1XRvPvVGc53hKX7h6vrNYQXunvB/ynWklDq4KGSgzZkFBDs0mFmj6g3H/Di7yFA==,iv:NRlVTk6eEVUKb60Q4U2xdKpxe6haZbuDfjL+g13hZ+M=,tag:U/R/99Xc3NuC0Sf582PYcA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NUtKRW9NSjRucjhLc0hS
            YjYzOXVoVDVYbHVLbnExY256bkZWODJMM2xjCmdRT05sRmwxaTNGUnhUY1BiQ04x
            ZG4xbzRBck8yV2s2QXI0Z2hjZHc5bmsKLS0tIGdkVHd4ZnVjR29xd29EMVRLMUhO
            dVhDR3o3dzgrNEJpT2lMeTVhNUlYa2sKksFJGxgirJusJhFuXzijbNx31DwefwND
            SdMffzb1550ucx3CA53LOcdv1DHyidp5YOUs9XwOLkkJQBKRuV9rtg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T21:37:00Z"
    mac: ENC[AES256_GCM,data:LQws0kystQOyEYWZEOceNcMd+vGU6AMUwJqxx1RAcKkAZ2mOwnAEzpMyxq1HEg+txTIyHnYW0hbHCnYWA5vJC8K5nAK9Pj0DX6uq5w59x2OzG2f2Mbk4R+H4rDwMlAln0GzaOCsVL8ztRxYst6x6Kf04VnJ06Yy2/ubLOpZcC/U=,iv:dhzLfGk3nnNssSHrBFW/UZmQKfhpwXgS1Q1v+7zu74c=,tag:sKkVj9wYuK4M8vvssq6KPg==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-creds
stringData:
    QBT_USERNAME: ENC[AES256_GCM,data:zaJgSw==,iv:icgN+Wd7FwoWnY6HW9Bt3frZsie6S6seMTXhHMenRN8=,tag:mQoZZrcSWOUHfZfbl0Tm0A==,type:str]
    QBT_PASSWORD: ENC[AES256_GCM,data:N4CZHzYdWeoATTQfp1TwWET6JH5LyeRvb6BKsgAlj7A=,iv:SVgugB3ZTlExat04zjhfkzYrW5Q1BmrW34TaNSuBhio=,tag:r6/As7WySeOSVP8mhc7Skg==,type:str]
    QBT_API_KEY: ENC[AES256_GCM,data:XDI3YcwzcIh+GwK4F5tHYxiosYWHDW/EGUMuSqlSBLw=,iv:4BvA7HHUWHqzjvgjq9VhyV8vRY4ZGIZVWkqE0GchxPY=,tag:FoBUoUiEHlXYj9qmQfSOrQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NUtKRW9NSjRucjhLc0hS
            YjYzOXVoVDVYbHVLbnExY256bkZWODJMM2xjCmdRT05sRmwxaTNGUnhUY1BiQ04x
            ZG4xbzRBck8yV2s2QXI0Z2hjZHc5bmsKLS0tIGdkVHd4ZnVjR29xd29EMVRLMUhO
            dVhDR3o3dzgrNEJpT2lMeTVhNUlYa2sKksFJGxgirJusJhFuXzijbNx31DwefwND
            SdMffzb1550ucx3CA53LOcdv1DHyidp5YOUs9XwOLkkJQBKRuV9rtg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T21:37:00Z"
    mac: ENC[AES256_GCM,data:LQws0kystQOyEYWZEOceNcMd+vGU6AMUwJqxx1RAcKkAZ2mOwnAEzpMyxq1HEg+txTIyHnYW0hbHCnYWA5vJC8K5nAK9Pj0DX6uq5w59x2OzG2f2Mbk4R+H4rDwMlAln0GzaOCsVL8ztRxYst6x6Kf04VnJ06Yy2/ubLOpZcC/U=,iv:dhzLfGk3nnNssSHrBFW/UZmQKfhpwXgS1Q1v+7zu74c=,tag:sKkVj9wYuK4M8vvssq6KPg==,type:str]
    version: 3.13.1
