apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-config-seed
stringData:
    qBittorrent.conf: ENC[AES256_GCM,data:fiOm6vWxYLW/viDPGLrQkQ50/cAvrbpryunfAIq1areTXIHoApsMu7mwopPttoJC7TBG6tzo2yXu5lFZpWkMjIzB86YMb9X5eGYzUu+nl2qcYIZXzryasblhmCUDW7RbVXxXL4aYX4BtQR2EvwHoQOPDaWdRzmPFGlGCkvWpkAqgoOM9qo0HSZ1YUjhofhLj+J86NVAPAvQ0x9QOq8xJ/R6D5tR2C/VNh8vTyCNQ/PQSn35Z3uN+fnhSwBgyP8coozivFiKNtqQEOjJAG5B6w8j3TWzMv6Lc9i+inXcqbSAUL2+SaoIc6doNNl4nCTotk98+AOPcPtkhoGNrrmkWpj3wZ7F0foPt3qhjcFfz0y3nRLZCws62drW2IEdJ1MMY74Y0FktoL/AV/VOBpDd4jtwH+vJL1I84LMKMKXKO325BF2vwMJ8JkOkkw1V/H80BvH16XoUJek1GzV6x+G8w2tc6wSS8LNlN/Wqc6jJ6oKXHSP7R/jJT6HtLt3CXpDDLHqT+28YolJYbBuVSSqDXUHeS44Qc8kwwT89AkE38qbJtrFc6MhUo96DMGxikhoeYQ+9I,iv:348mAFixEmbKu4puEjoL5ht8gNXiGTvHj5JbtN0jWPc=,tag:Hq0pFhQoP3GPeMrUIY/IqA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVb0s3TldlZVV2K0tvaFNW
            dkc4ODVXKzlkTGVwMHVWbnZKeGlwTlIrOUJjCmdzaHZsNGxMZDlRaUpONWVTZGJB
            MlJWZGJSWDdrSjI4SmxwNjV0ZUpLVVUKLS0tIGdkYTVvTzQ4SEd1WTMzUFNhci8r
            amJ0SGZWcUozL1ZLOEgyQ0lQN0M2MEkKXYArL1q1jTJdglWFFMLJnsa1B7tju3fm
            Wz/QT9SNg2nzD7cOdlEiYkZi+wn2Vzad8W61K6yuqHOIRsKll7iwRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T22:35:31Z"
    mac: ENC[AES256_GCM,data:gXSuDSxwEsXVmY8bZG9427oMsHRZYIs1eJVLczccF9tzXWGpo+7QGeg1XHlJdb1jzSkrRZb70pOhijYhUeu7ORN8vxbJ323dCZGBBfBtOKyzOqrL20XQl4Q+hxaaDcGM/VIw74AN0bah1Vbc3oal7WK/lcdHw5h4Qqqpw9TwYeA=,iv:s4e+AC0mHDyc+HQFdJeOb2/zbNExqL6BbTvXew/wW1g=,tag:vGhjGTAQrecj5cEggUjfEw==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-creds
stringData:
    QBT_USERNAME: ENC[AES256_GCM,data:s44U+w==,iv:OwE9gtVqmJrzk/+q4oBRZBdPduRaEdsxwS2+1v5gCZk=,tag:qZNMP6us7wL1LZPBVZ1cJg==,type:str]
    QBT_PASSWORD: ENC[AES256_GCM,data:4KVwzh/KK69HraMPY+zIa1LdVm59,iv:Hr11TIQvHjxGHCcJv9A3UWeJhhorNSCCCp3QjLDhsPw=,tag:AswrCwNjOW0/vROQiC1yKw==,type:str]
    QBT_API_KEY: ENC[AES256_GCM,data:X3uVA9ajXXZiAoNJ1dxvOwZkqvZiDo66cmOgxag3I/a3BINGo/YFGOu3d9ZxxIkJdWJp7Sj3MYkvT4mB68lCTQ==,iv:rZCcGhYaaF/bMgH4qi0qZKSZFjmy5EJwFGNUUNKkmMs=,tag:8XC3t337tTjTfKpFHoDYgg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVb0s3TldlZVV2K0tvaFNW
            dkc4ODVXKzlkTGVwMHVWbnZKeGlwTlIrOUJjCmdzaHZsNGxMZDlRaUpONWVTZGJB
            MlJWZGJSWDdrSjI4SmxwNjV0ZUpLVVUKLS0tIGdkYTVvTzQ4SEd1WTMzUFNhci8r
            amJ0SGZWcUozL1ZLOEgyQ0lQN0M2MEkKXYArL1q1jTJdglWFFMLJnsa1B7tju3fm
            Wz/QT9SNg2nzD7cOdlEiYkZi+wn2Vzad8W61K6yuqHOIRsKll7iwRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T22:35:31Z"
    mac: ENC[AES256_GCM,data:gXSuDSxwEsXVmY8bZG9427oMsHRZYIs1eJVLczccF9tzXWGpo+7QGeg1XHlJdb1jzSkrRZb70pOhijYhUeu7ORN8vxbJ323dCZGBBfBtOKyzOqrL20XQl4Q+hxaaDcGM/VIw74AN0bah1Vbc3oal7WK/lcdHw5h4Qqqpw9TwYeA=,iv:s4e+AC0mHDyc+HQFdJeOb2/zbNExqL6BbTvXew/wW1g=,tag:vGhjGTAQrecj5cEggUjfEw==,type:str]
    version: 3.13.1
