---
apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent-config-seed
stringData:
  qBittorrent.conf: |
    [BitTorrent]
    Session\DefaultSavePath=/downloads
    Session\Port=6881
    Session\TempPath=/downloads/temp
    Session\TempPathEnabled=true
    [Meta]
    MigrationVersion=9999
    [Preferences]
    WebUI\Port=8080
    WebUI\Username=admin
    WebUI\Password_PBKDF2="@ByteArray(EcOxZau1bupioaLqOEZCTw==:Qff6uE8Iur294AypH1CSHIO/+2ljCWfLHyTdDaR6yMhJdkPFkfS5ujdSiwMTY/fuP0SQxjHJyQhJMB5KpnY8Zw==)"
    WebUI\APIKey=d0db4ebdccdfcb2b5b4cecd4a2773419b1722162532d905ba0f5e5cfb9d708b8
---
apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent-creds
stringData:
  QBT_USERNAME: admin
  QBT_PASSWORD: "1tTJ-xe9g-G5Uj5VwWpjCKS5"
  QBT_API_KEY: "d0db4ebdccdfcb2b5b4cecd4a2773419b1722162532d905ba0f5e5cfb9d708b8"
