---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: misc
components:
  - ../../components/common
resources:
  - ./atuin/ks.yaml
  - ./copyparty/ks.yaml
  - ./forgejo/ks.yaml
  - ./forgejo/bootstrap/ks.yaml
  - ./linkwarden/ks.yaml
  - ./maddy/ks.yaml
  - ./nebraska/ks.yaml
  - ./thelounge/ks.yaml
  - ./tuwunel/ks.yaml
