---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: omada-backend
  namespace: network
spec:
  endpoints:
    - fqdn:
        hostname: omada-controller-app.network.svc.cluster.local
        port: 8043
  tls:
    insecureSkipVerify: true