apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: omada-backend-tls
  namespace: network
spec:
  targetRefs:
  - kind: Service
    name: omada-controller-app
    sectionName: https
  validation:
    wellKnownCACertificates: System
    hostname: omada.internal.oreillys.io