apiVersion: v1
kind: Secret
metadata:
    name: slskd-secret
stringData:
    SLSKD_SLSK_USERNAME: ENC[AES256_GCM,data:E6uHieGSb1A9Cf/lai01,iv:On+9cPwHxGJrqqrj1YLuLJ5vk+kUnRNvTmKhqmp1jPo=,tag:fxMlaEbKMSTZVJAov6/sMQ==,type:str]
    SLSKD_SLSK_PASSWORD: ENC[AES256_GCM,data:WiCj/exRByPT9en7CfJxc6pL,iv:lPc9/BHzKfYnJh0xYJPGPH8gJu+FWQOe3Y4wK0P6LKk=,tag:Eba4ND66POILTWxRgHXnSA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Vkw0M2ZQazhNaHhZV0ph
            SUtDNVptSG1LWE9USEdPM1F0WWtJbGJ0SFg0Ckd3QXNkalkzdzRCdWYrczJqY2d2
            Sy92cERwQ3F0c3VUTmxyOGx3MGxqeVEKLS0tIERiUnRidE5WWjdSU0dvYksrVmJl
            c0QwSm5VQXFCZk54cjBDN0ZJN1pnSDgKfv+w0lRBSV2F2vGsayw2kMU5kWWtB363
            HKloYYg4ptOf7ApqlepsX/52jH2fXtWGv3p2nPPFq0k+iTyAOED6tg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T23:02:51Z"
    mac: ENC[AES256_GCM,data:RkdU9p+10DYmXIUkwslKVaI173rDW1qcO/x3RxFZ6CoeD7gkPUAlzLwMUrUGhnJN/jKyOmQnVOEo6FJPjp0QN2ltOQuueLLBelaf4+O88oPDUDDQCyYQ10YdIbsB3Kfcr3MvSjAvvYILVWzsl4GZ4bCM9g/RBxD8p5TQigVo5WU=,iv:q8mJQg9dfTRejYrEusS87UtWAczxQysmyBmCHBncgtY=,tag:j9iTzdgonNmy78KIv1X4Sg==,type:str]
    version: 3.13.1
