---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./stagedglobalnetworkpolicy-dns.yaml
  - ./stagedglobalnetworkpolicy-network-ingress.yaml
  - ./stagedglobalnetworkpolicy-observability-ingress.yaml
  - ./stagedglobalnetworkpolicy-database-to-media.yaml
  - ./stagedglobalnetworkpolicy-database-to-observability.yaml
  - ./stagedglobalnetworkpolicy-spegel-mirror.yaml
  - ./stagedglobalnetworkpolicy-misc-to-network.yaml
  - ./stagedglobalnetworkpolicy-lan-to-envoy-internal.yaml
  - ./stagedglobalnetworkpolicy-opnsense-to-envoy-external.yaml
  - ./stagedglobalnetworkpolicy-apiserver-webhooks.yaml
  - ./stagedglobalnetworkpolicy-lan-to-loki.yaml
  - ./stagedglobalnetworkpolicy-lan-to-akvorado.yaml
  - ./stagedglobalnetworkpolicy-lan-to-fluent-bit.yaml
