---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./globalnetworkpolicy-dns.yaml
  - ./globalnetworkpolicy-network-ingress.yaml
  - ./globalnetworkpolicy-observability-ingress.yaml
  - ./globalnetworkpolicy-database-to-media.yaml
  - ./globalnetworkpolicy-database-to-observability.yaml
  - ./globalnetworkpolicy-spegel-mirror.yaml
  - ./globalnetworkpolicy-cluster-to-network-https.yaml
  - ./globalnetworkpolicy-trusted-vlans-to-envoy-internal.yaml
  - ./globalnetworkpolicy-trusted-vlans-to-envoy-external.yaml
  - ./globalnetworkpolicy-opnsense-to-envoy-external.yaml
  - ./globalnetworkpolicy-apiserver-webhooks.yaml
  - ./globalnetworkpolicy-trusted-vlans-to-loki.yaml
  - ./globalnetworkpolicy-trusted-vlans-to-akvorado.yaml
  - ./globalnetworkpolicy-trusted-vlans-to-fluent-bit.yaml
  - ./globalnetworkpolicy-postgres-operator-webhook.yaml
  - ./globalnetworkpolicy-changedetection-to-llama-cpp.yaml
  - ./globalnetworkpolicy-download-to-jellyfin.yaml
