---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tdarr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: tdarr
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      tdarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/haveagitgat/tdarr
              tag: 2.86.01@sha256:6ca12ec9989089b364e43b692a8eafb4c8d0ecc14151d86fd933d35717a1e934
            env:
              PUID: 1000
              PGID: 1000
              serverIP: 0.0.0.0
              serverPort: &serverPort 8266
              webUIPort: &port 8265
              internalNode: "false"
              inContainer: "true"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v2/status
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: [ "ALL" ] }
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 2Gi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        primary: true
        controller: *app
        ports:
          http:
            port: *port
      server:
        controller: *app
        ports:
          server:
            port: *serverPort

    route:
      app:
        hostnames:
          - tdarr.internal.oreillys.io
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: tdarr-app
                port: *port

    persistence:
      config:
        storageClass: "ceph-block"
        accessMode: ReadWriteOnce
        size: "1Gi"
        advancedMounts:
          tdarr:
            app:
              - path: /app/configs
                subPath: config
              - path: /app/server
                subPath: server

      tmpfs:
        type: emptyDir
        advancedMounts:
          tdarr:
            app:
              - path: /tmp
                subPath: tmp