apiVersion: v1
kind: Secret
metadata:
    name: thelounge-secret
stringData:
    THELOUNGE_USER: ENC[AES256_GCM,data:sHZ9rYE=,iv:STNXSbt+xL69bwxtB4SkHWtjssxEc7DqdQ0lhUg9maM=,tag:lWyEVe8vDQX3kQ2dSBTcIQ==,type:str]
    THELOUNGE_PASSWORD: ENC[AES256_GCM,data:Ww6V+/S7+oFvgToVaFlWeooD9Q==,iv:L2IlkiiWRqYva4q8JmVAMtUJhBWAjC4rfAs3i2i8A3k=,tag:AquXs5odThAjuy4+aDWpOQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZEk1aVp4QmdKbERQbWV0
            R3hXMVRmM25ldDBnd3RKU0tTdU9SVkpiL0dVClVSL21POVMrcEJCT1hqVW1Vclgr
            TzVjUWNWK2FRRVQ1VWFHaFJsUjFVTnMKLS0tIGx4RzBtRnQ2azZweFVHUnNMYURy
            SHJYa0dmQkpQMEFRZEptazdXK2NyVHMKj3LHC6BgkSzm/HvDU2ADNVqa9mU2gqk9
            R98USFlFYpHVnFvlgYGMfbDsqFCN5wEXk/6mNephc64fwi926IZILQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T21:59:10Z"
    mac: ENC[AES256_GCM,data:E3hM1l6V1K1u8zhMtpLBvJWE4xRyIzmYb6xzh/9Hqmuw8yekEWkRsrlpt9uf5lIF4DZ7gr29aFZB7/HySHw1lKuCSHC7MSEnD/D1dKz/y6Zv/Nxm2JmnFW6UHjXp18IS42zzmSniKFDHsQpX/FDFypK7DR0+3j9rTckmDJOGILg=,iv:fVu3mHaFlHqt2Q92nxES2MfZ5fZv37peCrX9qYo7PNc=,tag:WuhYavhbeuA5VfSen4zUBw==,type:str]
    version: 3.13.1
