# sops --encrypt secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: gatus-sidecar-secret
data:
    GATUS_SLACK_WEBHOOK_URL: ENC[AES256_GCM,data:bc9KvggNa8Z/XcGRYbbaGEofdb/Y30fEHePYEksMRKcZlxGfhfaYST5FosnYGGVtwxDDHhDDD9CLBtANXdobDN/tnCD4TSLavkS5FYKOTY6SYzedDnODS+mv2QU96hcCNbEComwXAX20ChZH,iv:jYs2YNDg9plgNS79/F8t3Y7SYCimUXqM2B0DopdTgYQ=,tag:SDtI/WVWZj0oYy0o6FkiGA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdEJxWWpWeDBWVnRQaGdN
            UC9rZUNUNktQNlhBS3I4dHllUlJiMmJVYlJvCm5zVkoweEc3bzFuSG5vYm5vbTdF
            THpjcjlwLyt5R2ZWb3o3UEgyc0tHdmMKLS0tIEVkV1ZHWHNYYys1NVRTOUV3bVdt
            NUZVbmowMHgvL083eWo2ZHkzSkMxZ00KRMV7bdOKKFJu3dX16Oi7oQAU1owrC8Ya
            d7vShYZjkucoMdPZPEYVPrdpjeTZebqhaJC6wgq7GJRLmQS2rWVgyQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T09:12:14Z"
    mac: ENC[AES256_GCM,data:hnxLVXJ7rC1K086yoWTLvN5XqpzabrtX3ls/dJs4Sj/Vp4QTWB1+loRvgU33XdJqi6Ki6jHq9TC5/uvhVVgErXENXu4dypv0WzQOgOMbc+kJ1ZMKtEOKFpfb/x54whjbeeR5E1ewInBIUjKV73DpvWfrasz3LBPYzlfmzZPWcZ8=,iv:OwZ7uG6pyMVaD0hWaivm96PLbxjD2fK07lyZwEZFyfQ=,tag:NIe0A6n9vPDWUsfNCY4aSw==,type:str]
    version: 3.13.1
