apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secrets
data:
    slack_webhook_url: ENC[AES256_GCM,data:OOzWWqUJlt1x+XPrh4kHREoQAB3IpYiYcBmIc5fGMFk4xgqUYUmmW6eKyAuh8zcU8RXJRSfj8uXLNFFbtA3H1KDWIG5YT0yuJtC5RE3vUcK4dJtiCzfOB7AiJBPLnd0qvyoMgShCYhHblyOs,iv:VFXXp8MRwB/0MzhPv3/hu3vb8/9SnIaj+Bk8aGPjPrA=,tag:Gj+TnffslhYbpsLWgErcew==,type:str]
sops:
    age:
        - recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueGljZno0N3p0eFFabW5Z
            VU9NWjFsRWV0ZTExRUJpL0F6UlNLVzFGb1drCnR4ZDF5cnZzeW9GWVd2YjdYQ3Nz
            ME53OFZJMElJaXhNYUlxNDVieTBuOWsKLS0tIEZ1OGJJZ3AzbGN0WXVYTDdmMUNU
            V2hzNFE1clpXMXRGdko2NHJCaC9nY1kKwAIeiHAGZZCrgQxgftP+0akWFZ8d21v5
            gdl+UUwF0d5G/5bmi3aQvcLi30DvUJJthwl96jclFUkiZW48YwRoaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-17T00:09:21Z"
    mac: ENC[AES256_GCM,data:ScEpOwEvKtb9yUMdglCrViXpVSBkEdrf4tpm7byP5NKsJBr6xwqrenvuQl/JexALHS8D1TeJcQ1I/z5gKvAt7fRR8dgzZ8lt/RoosX5yA1KHnNQfx7jpB0H7B2nWqT3Fc5DNeLYF38MZCOCJnXP4mAH3QzRYe9F2SSPLZ1lkW5g=,iv:cj7DiZsY5zykmon4v9N3OZoLZYOBqqJpJJxqtK0oqwQ=,tag:rTS13/DKyfFijlO5TGEraQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
