---
# Bucket + S3 credentials for this cluster's Barman backups (Ceph RGW).
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: home-assistant-postgres-backup
spec:
  bucketName: cnpg-home-assistant
  storageClassName: ceph-bucket
