apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secrets
data:
    slack_webhook_url: ENC[AES256_GCM,data:Nk6i7L6qBp0xz9YEcLncrmjAEnr1bIU5XPkJSTyn7yxWgKjZgGNPqZZrbDBFG/elmB3bxw1Deb+Rg0t2nRYstTdMt8KGwfsf6EGltVZr54Yt6BMZb1aVW+PqDzfaCWzIm1kJxANcJHv6R69B9ZKPqQ==,iv:e6UVOz3pZZyRF/vnStil82pC6LIoGW7nhFVlTeiRfB4=,tag:d1DvrN/IisDhEphsDAGjzw==,type:str]
    home_latitude: ENC[AES256_GCM,data:gpYCIon8rpzdSn2aAP00YD0ZHTzwttor,iv:rHoqpmTmpK3qCnSlAg8XsHj1wVU7m3W71dT28686+kA=,tag:QndWior4JTkqnmX7ekaCmw==,type:str]
    home_longitude: ENC[AES256_GCM,data:HWUG8NK9z1HAA6cORm58jsq9psURTdDJEJeUOw==,iv:MfOXihaU35hJaJYZxwMpljWQHMb0d94uoutUFkpXKA0=,tag:/ta76gE0GTjwG1q7zsljpg==,type:str]
    home_elevation: ENC[AES256_GCM,data:F+pK6w==,iv:VxN8YsuLSV8x6CGzdQxCj8BmFeU5wc0x29TAcHstDk8=,tag:SJ8Aiz434XbTzZHaLszV8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRXR5dHhDRUNHNWhUeU5W
            cTR1dUxFZi9jYXZVMTVPQ3ZoaDBxQy9Id2pVCjg3cWdqUnNYb3VvbXo4TzQ5ODl6
            aStsVFVIemtxMHVRRkVhVys4V2UwcmMKLS0tIHZ4NS9jTnlpWW90UlNzYUNmOEFH
            R1dlSCtZcS9MK0Jwdy94S3kwd0lOUlEKgvFIqGw3V0dLiMuvUCgg0kYTtteMQOhT
            Jq4hFIw56RQY9UaiRysE/Mais9IknvUAGWZK2AgbDM0l7TgRD/myGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-10T20:01:03Z"
    mac: ENC[AES256_GCM,data:1r6Fe8kiVFH4LRzELnVW1FcwQxjMxSxAeG+1gDkCWNW6k93BFKJKp2hUe76tvIFzyz+cSDfG9zz+hqWTddAdgOBYNTFQain/ijs9CFBFlKiKLLMMPxi3NHZwoiVWXrvidOYCeJgJTsqNS60hO7NUVOHqI0BMZ2sSUyCDwsOfC2Q=,iv:ZYnonkkSw03x9byMoKK8SuxYomQglAmLKlQEDq3y/4E=,tag:2fzREg6QZxN53bdgguiZHg==,type:str]
    version: 3.13.3
