apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secrets
data:
    slack_webhook_url: ENC[AES256_GCM,data:pmNUAbaGFGFwaCM1IyQrVYCD9XQIfNvuLPAQQ4Fn5PStxuVCn31Y3ksnoiJQK+3rFgAidh+MDxUKRn2cmjsBLftSu/CeEbZpYEQ2ri+7Sit/mzOx6UjbFR8NvnooNRlObo5b4E0GEllJ/xsG,iv:/oYwaVnjVIxT48PkWxsZnd/FaF2MiLKaMu8tEzCi+ms=,tag:3GFGbR9mUJtU77BXPKOUgA==,type:str]
    home_latitude: ENC[AES256_GCM,data:gpYCIon8rpzdSn2aAP00YD0ZHTzwttor,iv:rHoqpmTmpK3qCnSlAg8XsHj1wVU7m3W71dT28686+kA=,tag:QndWior4JTkqnmX7ekaCmw==,type:str]
    home_longitude: ENC[AES256_GCM,data:HWUG8NK9z1HAA6cORm58jsq9psURTdDJEJeUOw==,iv:MfOXihaU35hJaJYZxwMpljWQHMb0d94uoutUFkpXKA0=,tag:/ta76gE0GTjwG1q7zsljpg==,type:str]
    home_elevation: ENC[AES256_GCM,data:F+pK6w==,iv:VxN8YsuLSV8x6CGzdQxCj8BmFeU5wc0x29TAcHstDk8=,tag:SJ8Aiz434XbTzZHaLszV8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRXR5dHhDRUNHNWhUeU5W
            cTR1dUxFZi9jYXZVMTVPQ3ZoaDBxQy9Id2pVCjg3cWdqUnNYb3VvbXo4TzQ5ODl6
            aStsVFVIemtxMHVRRkVhVys4V2UwcmMKLS0tIHZ4NS9jTnlpWW90UlNzYUNmOEFH
            R1dlSCtZcS9MK0Jwdy94S3kwd0lOUlEKgvFIqGw3V0dLiMuvUCgg0kYTtteMQOhT
            Jq4hFIw56RQY9UaiRysE/Mais9IknvUAGWZK2AgbDM0l7TgRD/myGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T18:23:24Z"
    mac: ENC[AES256_GCM,data:yu8R9KGvqdNcLRUDzHjAOhkL9pGoxp/E9uH0oNZIqgI0MnjWhIhrmjWLxyRYb1WeEjhnQw510Hjur4T1gxZh0HOG++yLQT3PXOEivdjisGeiShy73szCpewpGQy4BzqWH9Dln1IToBLp7l6yNKNhLerDnt8iQSEs70qiVv+5Ir8=,iv:dUS41I/AADKmNA9tbNPL0oG64aiZofkdZVN7C2HRKPM=,tag:4Fj/ojs83PU6hQV+EOFUzw==,type:str]
    version: 3.13.1
