apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secrets
data:
    slack_webhook_url: ENC[AES256_GCM,data:gUeQaDiR4lc=,iv:EQlGMj2v++o2RndrPzv5iJpyiMRGfjmfTxg1JxmVxE4=,tag:zzGcoin+Ms27xLuMa44E+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYk0vYjJDd3M3NXhXc3Vi
            RlAySDRYcEdxeDZzZ3hHczlhVU9vSUlmV0JZClhFMVZ3YnRGT2pSVUQrU202QzYy
            akZQVXNtT3IrOGM1QUFxUjBTZjBBRGsKLS0tIGJEMGFKdUFTOHhCZ29zVUNGellN
            SkRlN0hPRW4vUWRJRkpzSUhQWmZxa0EKNPgV35kzQ1LqnvUn3cwRimzJ/XJ5Bf0+
            IikEk67OUOSj5PVmP+N4nNF3skp/EzxASx+i7OlH4JczUcVMfktLLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-09T08:06:57Z"
    mac: ENC[AES256_GCM,data:A48AtOFfy9PgCFO7c7EigZE/3hWFeQ6f3LhowKKvGDGYMBrz6efLeFGaCs431TTaEL/Lf7STzX5Dy/MYpB0HrFuIUv9Za48VeX8R6xNo7L8nPVUI1jMH/tZEYjgYCBYMefz92fCElNZAIGZOM60MdcUmfvJBY9N6G72fUbw/czE=,iv:BVcu/oUMEE24qplFIH3wP8iQX0tJ2lLC49GY10rZJeg=,tag:/JMaNCcFSnE3LRSBhC8Gew==,type:str]
    version: 3.13.1
