---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kopiur.home-operations.com/snapshotschedule_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: home-assistant-config-nightly
spec:
  policyRef:
    name: home-assistant-config
  schedule:
    cron: "H 3 * * *"
    jitter: 30m
    runOnCreate: false
