---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kured
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: kured
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    extraEnvVars:
     - name: KURED_NOTIFY_URL
       valueFrom:
         secretKeyRef:
           name: kured-secrets
           key: slack_webhook_url
