apiVersion: v1
kind: Secret
metadata:
    name: kured-secrets
data:
    slack_webhook_url: ENC[AES256_GCM,data:uBb2L9gKPa47fFzjdTQ1AD1Q9Tyf7cnqJl8mRru84Obcb76NUjWw4F/uvqsVodR87yv2pJFXGck=,iv:az4bXmA9ZapQ0iSwVm8CW33FA83yXW/ZdM0479z7pV8=,tag:w7YQLpzC0N4fSQ2gdhkEOA==,type:str]
sops:
    age:
        - recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYczVadzM3MHFqR0dLd256
            bUcrMElFRERRTHlWbTg1ckVHdFFqQ0p5ZmpRCittQ09HSUNaamFKZUxDWUNwSlFE
            RkdxUzVBVHBtS2s3UWsxVlBZNkFYSmcKLS0tIE9WdmhJZ2ZjcUxlclEyS3JGRlI4
            VW9ZTXpZSHk3SGVVRk83bVVSblVLek0KOZMpO4cnGBo5mTVvK0Fd/5ZSkdgrwTlj
            rEVvtlRiMIdeSmejSN4PMWVs0TbKHCMV4Odl57FAy1GO2Uxd44JU6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-15T20:24:49Z"
    mac: ENC[AES256_GCM,data:kzADmTHKzjiSt1sp0D5CaRs+2ErRDKz+Ufjt0r9uWkT30T1m/o76FfkfPM29R/0v09+h9bxxkSTgsyk2cAIKqF6pfFx46ADMjLwcUfRgqk1ecmxJvpKz2DjQJ/bBAv9g3HfmMS1LhG3ECDd4T3o7rntKPO95/jwiB1j1zLjBFdU=,iv:on+adJX5C3XN9v1N6lLGP3bUwL8NsyLYqiqhHKMPM24=,tag:SmWmC7f8sIhLDZRd85xkHA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
