apiVersion: v1
kind: Secret
metadata:
    name: maddy-secret
stringData:
    UPSTREAM_TARGET: ENC[AES256_GCM,data:EvRSWVQD/hQYrN/aO6dyQjQuNwmM4OzWtqkXBie67GwN2kzwdUH88a3hXJ4=,iv:MS9NXXdZ3lfE7tvOiSr37+o3M8XbX1Ry92UgbOLzxMo=,tag:bWAOCOeKbzmSjoRJiu+euw==,type:str]
    UPSTREAM_USER: ENC[AES256_GCM,data:uF6jRdzOk5CocDULxnuQ7DInc3Q=,iv:W1f2t9nPIYEqZVmnwpCaSKrzw5m7JBrSXt5FxA0in6Y=,tag:Q0AZuaKeTaSNEW5v5Hdt9A==,type:str]
    UPSTREAM_PASS: ENC[AES256_GCM,data:gGdhs56pgMPlUnVXPAwwIKafxTCsglCgv5QA9D9v8nPdwCf99aQO8Hhj1hk=,iv:/A/b6c1BkIvmOjukyrYhU+reCN6VYFwP1/kHS5EeP4c=,tag:69ejDFGn+wvdtSJmR9Z9+w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdHpnU05rY3Irdlo5MlQr
            RU43SjY3UlZCZW8yeGJ6a0Y4a3lWZ3lSSlhjClh2TGFqL1dvdWV5Tys3b2ozTXNu
            SVRkTFVWejh4aDl6US80VWtsMUUvN0EKLS0tIEFybFRFUzNITXhZcFcwdVdsOFJT
            MkJnVGU2MHZnK2ZzZm9iR1pkeHQ2ckUKBrK/CwVQrqiEOR5wkWTiYPsuqxcuSAeo
            C5Y6jShPiT2WTGNngr9cCjEGn1udxHSVkTwbbrmgt/GPbegGVlfDxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T00:56:02Z"
    mac: ENC[AES256_GCM,data:NrGW+QnYCbdWCTLZCX6vIZ3T82ZxxhODNEZnrH77QIERPek1/jAv3rlkKh/4c1PdJvXSERzP7465WKvoKfGd+fBDER0Jw4c9/Na+Woh5DIRjBp0utVY+sTrhm9Z6lS0I7XcMd2TJw9rA2BST4cRavsM/IIYUrMRV3x6676DFGiY=,iv:ihtk9UlnpuvW4+9WylWN1aWyMcgFVELOZi/gPAtwmII=,tag:g4EospKf21AthKO5/d5b9A==,type:str]
    version: 3.13.1
