apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-secret
stringData:
    PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:qVIXuj9jCEbU5A3/qv5LxU+Z87kSacgJXVv34LHqEdw=,iv:jOAhob0Qg5UwsWdxjjbSMA3jZ+COdJReu37yFkhfY54=,tag:xnMMOUgUiM4wbNjtFb6Bdg==,type:str]
    LAZYLIBRARIAN_API_KEY: ENC[AES256_GCM,data:6CNgUSD+m0TxIgD0Lwo/SbkF6HmfgOwBrRyFSObVvmU=,iv:U2mpZHU/nKmFHZeBbCX8sUNlIUNH3J4Emb4/jweAc0c=,tag:/pHEfo8gEEwtZYitIDjlgw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUK2VMR0VJUmRiSElvT1pr
            TFloMmJiejEwK3Nkd3dSSzNtZDQxQlhkdEFjClYxRk1OWEM3R3liRmZ0aEZrZE11
            bUd0alBRY0ZQdWdja2JXS2l3TVc5d00KLS0tIHEyaFdVMU1Qc0VMeWlPY1l6MjBq
            KzJJa0hVcmFlR2JQLzU4b3hNcG9HNE0K7tE7pYK14d32gAvclYpKD5inFRj6uzy9
            kZBykrX+N2lCscfj0Cp9PTTZQXEyl9N1se9ZOfr5R4GPwCXQHvzEVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T23:57:34Z"
    mac: ENC[AES256_GCM,data:zIUfriNfMcelh/nRq+reaU0Cp/kbo5csLxzmE5QUUUakbYTxijAd7kRztCZUhTuzniemgUautkVurmsWnV0QYwzm0KLoAOlxz4Mf3K+yS4GfdSoBjQzCWRl6BU87ATWRd3NxnLd9xNZInj5s773zOQvSH0ECnZLf8rLArNMpwSs=,iv:vIG15ht4vwx1AyFtvfUH1DLzn+jXHgo73iFQ8MSnFp0=,tag:m8vcp5WDlbfvcoS8TTgeyg==,type:str]
    version: 3.13.1
