apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-secret
stringData:
    PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:qVIXuj9jCEbU5A3/qv5LxU+Z87kSacgJXVv34LHqEdw=,iv:jOAhob0Qg5UwsWdxjjbSMA3jZ+COdJReu37yFkhfY54=,tag:xnMMOUgUiM4wbNjtFb6Bdg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUK2VMR0VJUmRiSElvT1pr
            TFloMmJiejEwK3Nkd3dSSzNtZDQxQlhkdEFjClYxRk1OWEM3R3liRmZ0aEZrZE11
            bUd0alBRY0ZQdWdja2JXS2l3TVc5d00KLS0tIHEyaFdVMU1Qc0VMeWlPY1l6MjBq
            KzJJa0hVcmFlR2JQLzU4b3hNcG9HNE0K7tE7pYK14d32gAvclYpKD5inFRj6uzy9
            kZBykrX+N2lCscfj0Cp9PTTZQXEyl9N1se9ZOfr5R4GPwCXQHvzEVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T19:51:17Z"
    mac: ENC[AES256_GCM,data:Wraq8o8Guv8r6x5Jk76oulJLpvWyLcYBjpE0ojTIgP2TOA1zgOBfTGrjjQVk5DxOYVeI5KsyWswtA54jRoML4EVxXMrNRyGhN/NlwjLoEKGgPrBiClD0oC3DgAYjkWT4VoimMOH8u5ik4pVtdD0yB3waVJhgCijSXO229e4cWAE=,iv:9mvhQBiaU1TZ03VUUsAy3E0UB+lAF7XEQPLpt8iTyo0=,tag:mvP4pGLZkTi0XA0RroN1kA==,type:str]
    version: 3.13.1
