---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkwarden-postgres
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17.10-standard-trixie
  storage:
    size: 5Gi
    storageClass: ceph-block-ssd
  bootstrap:
    initdb:
      database: linkwarden
      owner: linkwarden
      secret:
        name: linkwarden-postgres-creds
  monitoring:
    enablePodMonitor: true
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: linkwarden-postgres-backup
