---
apiVersion: v1
kind: Secret
metadata:
  name: linkwarden-postgres-creds
stringData:
  username: linkwarden
  password: "77688a8c19599ade6a34d6fc29c87b5f9b80a23bf74a6417"
---
apiVersion: v1
kind: Secret
metadata:
  name: linkwarden-secret
stringData:
  NEXTAUTH_SECRET: "tXZNh6sZTltsQAl7n+4zItGhRwPIVX4F9QRHmjw2+JI="
  DATABASE_URL: "postgresql://linkwarden:77688a8c19599ade6a34d6fc29c87b5f9b80a23bf74a6417@linkwarden-postgres-rw:5432/linkwarden"
