# sops --encrypt --in-place echo-provider-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: authentik-echo-provider-secret
stringData:
    #ENC[AES256_GCM,data:K+sEpE/UYe7cV0aLTQufIh+8mnEJ4g/7051cLzMH0Ls1khUBU63xMKShwtMMSWsdBrkwM3wINcsU4RK6m8s4GpN4wt8NsM1Gjw==,iv:N2+5eErirLAIy7YUROgniD3HEyFSTNnzvuyWXX4pNr0=,tag:FVpoPg1Wbl8Omw7ilHRo7Q==,type:comment]
    #ENC[AES256_GCM,data:cqCbRPjE5rowuX7/fv9lA7v5c1V4x17oJ4k972Ktt/FKlyd09qs2AfkEtesJ3VWF6m8/qMzGgLZf64hY3Ezdpw8K9tE=,iv:as0Hnmtm1h0uDjqXNr/6UQBnwcRQmWRxhRiAK1ZLH68=,tag:gGKEXdJJSNhfy9SvKFx6ow==,type:comment]
    #ENC[AES256_GCM,data:YxEASRRrSxy2P70yBHde3HW+ZtzGxoUtWnDUsHxazt+Oymvj9g+NgoUjJckrUJ1xbpyU/Mz83Q5UA6mIIXtgjU9fBmYPyIZR,iv:na3nTE8TTArbH1EoIue8f4UbsLHxhk3nGL0/9tidRrk=,tag:m/A62KM7VwI7gMCJUriPBw==,type:comment]
    #ENC[AES256_GCM,data:yd7VwVqGUlta3GGiW9wyo5Y3rzXmu8QrcESEGkzQadZ8Ch73XVjznhtnjoTNAEA96yLHzNh0uxiN7Q8/5THw3YySoQ==,iv:BkF8taU2pee2jYlcE9YgdHV/x2H0K0/7Jsr88VNtxhc=,tag:BijowBiedNgFBLziAqfSlA==,type:comment]
    ECHO_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:fUYtsLF6TJ6LiK//cERdFV23PDuYcyr5YeiL2TSiB40lMW+bOZqxtw==,iv:udG4xyyhoqgH6x1+HLUMW1ojo/tl33XJ2ua9cKcTO9k=,tag:vGFhOXw5v3ir29zLDlZz5A==,type:str]
    ECHO_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:a7ezASsLUFHJJhpHRCvT6TnxsDb0G63me+3I1Ob7r+5j2Awa1NLMtVe9B3c8M/Sth6zLdjPR5p82e0sYn8kZhzfCG0rBqDbNsHBj9c+REgE=,iv:+8xNHISrs6lFMl1uwwXCbG1uFmbJpoqUT5Q6xEuuS2Q=,tag:z1C5zcdOexdx8gHLDCntqA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSHVvQXROL2U0T0o1Unlv
            bDBLdTc4OGE1M3pvWFRwLzRVNWlHcXlyUm1NCnk0eW9hZjNMck91K2EwN002VlRV
            N1hOeVh4SnVRcWZSbGVwZ3pGblI5QWMKLS0tIEgxRldxbXBEczV0M2JFS1U5Yi84
            aWlUYkxTMEZ4V3M0alFVM3J1NGF3YU0K3CbFwfQC0niLAx7Ywq1ZGO/9wVCcczmD
            jj3YlaYlTZ6tmJrKBAl7erpBnlEWxAIKwVOEjQyCUs+a8DCudKHP1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T17:31:56Z"
    mac: ENC[AES256_GCM,data:LS8KA2Zc5zAEcJKJl2D4HtcBtTmpWs6D12uDJiDDpg+sSpu0EsxU1DK5n8DbzFQgmB8csVAvXqOoa/7X3RhfTKiXz4/yXxVTf2fxn+YZ6LZ7jTiD6CTR+mA6Dn4lhSDkDb37tygdg9shvjbn88mocbHIS/BPGUaKQUV2onfD/KE=,iv:zP/ifuhJTD+17kbPcfzJAJUeXr1SVkJ/Ggpm/2QGHZQ=,tag:nSJ/ZIDfnojchDmYfyeJkw==,type:str]
    version: 3.13.1
