# sops --encrypt --in-place grafana-provider-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: authentik-grafana-provider-secret
stringData:
    #ENC[AES256_GCM,data:FfmXH/xgGjICWi6IIXdx8PEKFvgXxrCGn00IU0ls0agJuUknojC7aHluz/cc3mkPOXfmysVuP0963H9dwn1E0haURtDfx9t4cuF/,iv:ljUIDv7fp9HE0NIKFzkv6E8osWhg6QGQ8hbERXZ9JkM=,tag:RSRn1OPggilxE6BI3DQEbA==,type:comment]
    #ENC[AES256_GCM,data:q8GelP3+MDLWiG9F9A1P3JsLKexXAuWS+IN37YSQBzE0fb6WqmGc23hgELVmmG/p+LeHUfg0VEmCI9lH0WwNEn0NKQ==,iv:agcvuqVIS6qXX16S4wolEqk4cQB/ApqbJp0zeH7HjtM=,tag:o5Ki2uYBfOM0essAEL/uKA==,type:comment]
    #ENC[AES256_GCM,data:oqrOQ4EpjirA5f1V7Vr3fOqKup/pDeQFilTadateSnEjLXdrBOxZghqP,iv:iQzWNNws3aR/TLkkeSBUFLZ2LCW3N6V8rVlTrQnt3YY=,tag:1k3omftX0XhYZB20NqJYwg==,type:comment]
    GRAFANA_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:Xr1LFLGUFyUKYCLYP6+ocRN5K1tEdCI6inEZPPEYmCP2ZUP1+a58OQ==,iv:4a0s7gAtOqyPGODGtI/jvkO1Af9+J9CEWViLkY87xcw=,tag:oI6N/2+/d1T5tIl6Zi6H3A==,type:str]
    GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:B8UTEo49vlsbhXfRF9bX6uNW9q6mc/oPBwolLEZ5iFUebMTx2PIPyXYbxoZh1EY6KoNf4h62STieozBUasvuaMulUkMMdubrdwFHxwg++Zg=,iv:hWYGnsDYVdw+fUyscTpyBrCK5sDSd2V9PdlNwA8VenE=,tag:q4ayFOZAc4L5xgwrdBuOfw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TS84bGpkRnJneUQ4bWJs
            OTExWmIvTmd4bm5sR1owaU1Gby9oSVhUZDNZCjNEdFovM3dGUUhGTURsVHV4Tnkr
            a3RnMHZNRDQ5dk5JakpnTDNtM2hYY1UKLS0tIExIaFZuYm1oRmZWM3pCV2xzaE9Y
            ZGtjaXMvLzEwcVovMUo1V3p4RVV2MTgKCBr44uKOYovEVFyn/8zkSxrAHo+muPWM
            2TkRuDcP/LX8f5JiJ4V+waFbFVGFU3Q3drDpLYOsv3Vzg/PeRZ8TwA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T17:56:08Z"
    mac: ENC[AES256_GCM,data:4+4pOcAB4KfMypIh3IJwG8J/uinFNGKEzYifQRlYE7xjuRRGLJkCQMf8qAnxqQ2sX0Pydw1Br6HAb9+lFoisp8l5w2zp60bMin4je5gWKIyct8F5kKGEO6Z3tFW4pruIGKJ7ydj1qDdG0/mNCJNXJAKNKVagY9tjNKxnv9HTVoY=,iv:3fWogjCtdtzpL7QHPLxKRn50/0olwTuVaPjusHHBe48=,tag:ptK/1zUg+disNPZpd+HY3A==,type:str]
    version: 3.13.1
