# sops --encrypt --in-place kopiur-ui-provider-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: authentik-kopiur-ui-provider-secret
stringData:
    #ENC[AES256_GCM,data:cazl1JtGHyRevg+4GMJU4yV0PZ4aZEq88Fjo8rA795X7+t9Vchkxu+3NeDF10evU2k5Jleg4NJfVRLBRell0ShnFfmEpUVZ3jy8d0ppldNNKy3jAFeaVhw==,iv:z2ZllWT8krz/SQOm8A6T0Mw3yStDNzybXlIq9mrpfIc=,tag:paqdbY0MMWei8zKfRolokA==,type:comment]
    #ENC[AES256_GCM,data:cB3xyRAPEfX94/qar7UZ2c8M2twhT1sxqjNdG9b6Uigr+ajvNFYmq/8NLs8Oyn0fNN8m+BjGeppOc1lzDE9yaGTKH38=,iv:jRxhvveRNiWNmNDFdDtZo+c6opNdlUgjX+w91G6izYw=,tag:r5DTK5B//JJtN0qef+IgPQ==,type:comment]
    #ENC[AES256_GCM,data:TkjDhvcNsQXvLZUUP8upE5Cw1uI9jWtbxvmMAET41I5MN8uZTwFzJwCtsryHKqtma9tOEWAuwkQj2202fLkPz+WI1TeREA==,iv:f4sywTaefddTRxeB1DesjQ2hRjqLX0sgYY39GuLqzbA=,tag:sz8nOOC+Zpmgg40hvNxz0Q==,type:comment]
    KOPIUR_UI_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:Kmnmo/6odsVdxM5UhWrltZwY4t1p6JjPNmoZIJl7S5wFU9pvTGX9wQ==,iv:HUSJW0RwwW/pbXmxPgb5hso6jHCe6k3NPsxAiNwFPag=,tag:tIEdERuUmpRhYeGiEYqBLg==,type:str]
    KOPIUR_UI_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:nIMmg9mtFFAPhY/E+rFmzez7KT/+WAbWDeLNPwKDfYiMk7NPwWvSddAjcAzDOoFezj6DZPC8ELcf27dTqDiggkpkH9y1brw6PQxr+1OF8NE=,iv:xLX4TITUPEdUY1uph0gPxZRG4dmzNpabNx0oWhf28EM=,tag:Qv9znUzmZ2v99FKoO2yHtQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZGRNOWN5MFVYckwrbTc0
            QzIwb2tLWk9IZ3F0SVlhdVo1enRnd1dzOXhnCmJpNE12ZjZybmhzZi9aeHlEV2Jo
            UDRBQ2ltVE9Ea21jNXBBYVltaFFKMFUKLS0tIG9LSElKM0pXSC9mSzRvQVI1ZDE2
            VVh0UTNlZldSbURCMDJwOHZhZExVTTAKmuF/npIjumQuxgZV8W6ZkYM/myrCzggU
            5OtV45DRyYSjVaHQGHOu71wJcayp7Wl0+enlkkGoHwlrpBTbzb0gWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T17:32:00Z"
    mac: ENC[AES256_GCM,data:C0f8BP+NchcurfyUkotql6UNRBx9TDstiRFgfa5pvlksjDNxclxJQK5yJ3D324QJX8b5kDYzVfHT3cvItOPn45RjGx7JaCyoneTMkeJGUmlkUIrHbhDjTLbNPHMI+B/Zm128j5VPLkiI/Of3LA93iTLZ4afwWElLWwuuiHOv0g4=,iv:mwsabrCERWTMBT8YegqjY/BakA+QjxFDM79ksAmUrYg=,tag:9CNiYSnSSi7Fb6rAgFR3tw==,type:str]
    version: 3.13.1
