# sops --encrypt --in-place oauth-sources-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: authentik-oauth-sources-secret
stringData:
    #ENC[AES256_GCM,data:77LB2rAbBRNEg+7MC2H0OGCuDV5cuI65ROvJsTQe4j3+4z2SMjpIZnR+qsHyWhJfRf403Z6FVcuepDMaZBB+YMt6Jhnk9ivm,iv:DTVj+h/psSF3APe+veeu//YzTnKSY7Co/sOpjxoawLk=,tag:PF+NULKjICGKbwbi5pe3gQ==,type:comment]
    #ENC[AES256_GCM,data:Qjz4EtoG3VE9ZQuZtcbReyLa6XfJ//7Iv3GXOoyI9Tm9HiSGQtPMwvnG4PIjivLN,iv:WvN3n4zMHKGhRPzIjsnXQuUBxH65BhvDUC/vkNAX74M=,tag:LkUg2IwHMxPtjq6Ofdki8g==,type:comment]
    #ENC[AES256_GCM,data:9Aq7aTrNjSWmUTUXGJso1z6dbU4/iAbMGJLFUfv/pucCyX4z/oUmxGRt6ldvltiMuQqQyckiKibldnGJWJtbkBpMl9gP,iv:N1/N5eGr5NlpueUdAijemEO3cm6zbILnPWUA5/qMqJM=,tag:5Z61htic2yvgrIAS3IdxrQ==,type:comment]
    GOOGLE_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:8o3WK+4Xd5lho1DZlA20WVZQ7rQmFW0ROQcRmsRYBJ72mOmsrM2VF9rpMvAzImU+t+lX7TafCWk7ej+t6i6si3kggTuFkVWq,iv:it124NCgmkCOwVc+iL+4O4nV4vX179CBt7dgM44N5m8=,tag:kGTyoro/9QQToVQYUsqJZA==,type:str]
    GOOGLE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:f5g8MSftEPuN5T0/crM0QQx1gxpBT5/GfYP7MfH5aOiWbac=,iv:QVnk2jGS2M+aixDPmxL0OvBo2FawBEjB6OkCBjYQ/28=,tag:DERcq78dYRtWpeTAS50d2w==,type:str]
    #ENC[AES256_GCM,data:gTv7fJotioa8TWV0D6nXdxdE00YBqpGWW9pPnoxuoKSuIExEhFChsIkHuKl4twxrNok6isLff6ZgMx+AALXA,iv:j1dSFzQlozy2vYbO6wS/QOHqolc7R3/c+u21JCXPZgs=,tag:rBhKIajmkDOdEGbM4/okxw==,type:comment]
    #ENC[AES256_GCM,data:6dniniX3tC17mVJnrJsCV/JYDzqyyZDpxAHPxooKFwKUMf0ySX0U/fCwObOyHasrrKpTL6oU576U+nPsC7YHL2hfeUPs,iv:ZussHHPv6eMG6hO4IXehqU9bhMMNetpO6aF+9Ywi3EY=,tag:s3x6deiwYgDkPui12InjZw==,type:comment]
    GITHUB_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:aZf9/4PobuyBts8Y5N/ilAJQ/OU=,iv:mzoyQYue73l965Q0UagiGmug/Y1tW8j/oChWr1rNC6E=,tag:IaiS6FzkawXtC4XRsM+W6A==,type:str]
    GITHUB_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:T70h7S7XI5QHEKPHcFxNuQU55qLXzTDblVipmu5nTu7DNeKOx6Vktg==,iv:PJzniDa6n4R0jznPJoJ6f8GjswvCa1/lPfch393iVXU=,tag:db5JJ946TVOwZHD8Tjj0tw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNFFFdks2NEVQbUxNSG8x
            SVNscDRYa09vWnJjR3lBaWhiUlFVZjJGL1ZNCkIzUzFoeVE4MWVlNm5tREFINHJU
            eWVEdzd3V2xWUk00eWw5QmdlY29SUzAKLS0tIHppMURXMHR2Q09xTlY2NXhxcGNN
            MUtnSmhyQ3BBM0xReFRNbDVlYlBoQmMKhzMllwa0SVWWelK6R73XrCADJ2n2GIId
            RFhRUWA3fztPNmdOljmaUuX6Mscmmob4xnZd9kgPtShAj6az2ylHEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T02:58:52Z"
    mac: ENC[AES256_GCM,data:MNQGRWQ0+6SNKnJrpM2WtOIjOZ8jWgjxAcGXt0yM5I8JLmlgIWP4c6G7ndESgM+7o3YtW2lnGYKBVAf7+CyIlxw/J6M35bzYeWGqjQibykNPg/IWiFJ8IzZgc+k4h0E5Qkg8Cgcxw+Tk3M97ZQVWxaYbjeShWcw7QZrbIVkPBuk=,iv:gYm9SjNghH96azKF+iwnDzOPj3RpdqwlGCmW0rB2uf4=,tag:EvHVDf6khDdLVQOYQxWI2A==,type:str]
    version: 3.13.1
