# sops --encrypt --in-place oauth-sources-secret.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-oauth-sources-secret
stringData:
  # From Google Cloud Console (console.cloud.google.com/apis/credentials) -
  # OAuth Client ID, Web application, redirect URI:
  # https://authentik.internal.oreillys.io/source/oauth/callback/google/
  GOOGLE_OAUTH_CLIENT_ID: ""
  GOOGLE_OAUTH_CLIENT_SECRET: ""
  # From github.com/settings/developers - OAuth App, callback URL:
  # https://authentik.internal.oreillys.io/source/oauth/callback/github/
  GITHUB_OAUTH_CLIENT_ID: ""
  GITHUB_OAUTH_CLIENT_SECRET: ""
