# sops --encrypt --in-place secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
stringData:
    #ENC[AES256_GCM,data:CpRcXhEKFWqUVLDCzi0WsUdK4TRZxnHeR9inlGydOQPOSV5/RBLF/SUOGC672AZRY31tEUfM8P5yBxZrp1pnuQnia5R0fkeQvQ==,iv:usDlRcAsFfkcdwIgikOcObm9e1iautARU9gTVuLEIAE=,tag:n/frxXUgyyiDZTdXPA3mvA==,type:comment]
    #ENC[AES256_GCM,data:l3h/yPWhSJUoeSaHTU4IwgFsL/f6NJ6ELYUeaQRYV1d4SqaHkY2Hmqr8Ao2gyGC1a9f7cYEh9lNxYi0b640=,iv:4p72RhTQZJSZabrb+C4ADXhdN8GWduZAJeSGGljmpEE=,tag:YVf+eAMO9lkEDDkZWP2EuA==,type:comment]
    secret_key: ENC[AES256_GCM,data:+C39KtAViFXL+ICuBcoKuSmeZISp7EcnZwY7cNsVXvY3qhecIzXFKcF4Zllxv3lXbtZ/XGUN79y+3NrPFM8SPQ==,iv:aGFeeebKV9BiSnN2zI1mJemvXubCezj9LmemqbZmrZs=,tag:PImJbXPNW44R5pUc4/2fNA==,type:str]
    #ENC[AES256_GCM,data:gcTi1lojop64B13TbiW8JUnoFo4Yj2TXyS8gNA4Fg7IuJ+BZ7hXYkoI7G8s4tb4A7SXEMBHlBDP3n7BBRrglYdpBEtL64lc=,iv:qPCDv6MHZ3o51//uuMoKAqbPLdYmvwxFi7XvAaXlqbs=,tag:yBLXTeljPCHuz7dXzHIXSA==,type:comment]
    #ENC[AES256_GCM,data:GFbu2UsDua0iHgxSsdQ2RWOlPFrrdS6onO8LdYrle9roIXZXFYN5Ss4iHahP2Ljqu0iiMv/91IGvJyInvdstfV2jdiC/2s7mqjo=,iv:eodvjusGM4uUrMj2bVOBq0poY8T0RG9KNHkfkJv92zM=,tag:fXPBWvLOLtgFnN8yVebkow==,type:comment]
    #ENC[AES256_GCM,data:KzBh6YCYy4/18LJwPosGRzuv6KkJBp3espZyM1LU9oB2xVkBoDbJr0906d8Tf+nYQ9LkYSveiGPqIjzqkRtQ7nI=,iv:o3q6FvrF3C+Pl6hEfCy1+B5NwO+Qcc7IBQxZ7yzvxhE=,tag:JZg/RmjfU7O5JSQhx3Zziw==,type:comment]
    #ENC[AES256_GCM,data:VeNVNyhcUOmYEc9jWMn2KSvKIfbd1KBxGCC5DJIEhDJ/L8bDtHNwDK/iXgJ180wsX8rGCfBcBfZePFTZ0PmX1RxvPuN9ihvZ,iv:nGo3Z6a02/Ewy6eNeLU2c1RlJ9RRSFkcXVZtHC74NMA=,tag:/jLlXgpFVTdF9D32ZzLuWg==,type:comment]
    #ENC[AES256_GCM,data:09rgOJ5QV+GEucYtCMAHg31axjxeJbJ1/GC/,iv:EBHtk3z6iluWnKlmayXPqa4H0995IOruQ9sqyErteaw=,tag:Byx4KlCYz2LZ/5tolXoguA==,type:comment]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:n+z+IU5+vqFIuDTRC7KEAw==,iv:LVpi3wcU4Gx3NXKRPtjUdRZA8wJDjIwUzUT15Hk2hYI=,tag:TBYFnhfDMffLmN4q4N14kQ==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:ExvmCVC4UxLc8cLYB4/cwVkwa33erYlPAOzYlPElCkwSSrjSD7WdTnyJbIfY9C7K,iv:YhRUV89X+XLI5ydBrEWOXAaCt006POM3XmJY0+5bUx0=,tag:7llmA/dw8bi27d3dH0ZOxA==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:6vXsZ2eRk2fhpF6JV1MDPI9oY4nGPC/5/GfCODwo9ZnrOWmHf8/poLrh374TZJXHkCzva7seeFzUBvfA4AWX0g==,iv:BHAyMLuShNX6kHUi/PmGDmSwIlf7X/6UVloLRMFkg84=,tag:B08yT5qAyxA/gKNImJgWMQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1anhQcFBCWnN2WTArRnhO
            eG4wR0lFcVk4NlVSRUJZdHlESnZWWDVJSFJRCnY1Z085bTBUam1PR0oyUEwxdjlV
            Y1VIeVBvc0JNUXBDZWI3aW0zUkZNRTgKLS0tIFRpcUplY01SMUR4cFFQV0tGaUp4
            aVlma0RtWThIa2d2WVZpazZBTjVsV28KlhtMKo0oXzAN3r0/3+zzdjZ+F1/RBqlz
            QSU8W3husFVnvZHl2U1Agx0QvMuPB5uSoMk9Oj7es6Ve/irSpxXw0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T21:19:12Z"
    mac: ENC[AES256_GCM,data:1NIzsXQ7D2Xzg8fmnTZlrWD3eQ+AgT5fIAg/2r1c3M63sKpYMcW6A8PapMPUN8CgF1s9t2SSCWH7nbIwaIDNuMKx38jgAl+xLk+A5tNEfNQKSQojBv0iwz1ZA3ZTFuIZ8ZhcnjWTlz9c+nlwA5/s0elgQfrCtORvlOG77mQrdHU=,iv:UNj0rO0klHFbv84/TgXqNty3f54GuSyUlTobl0W1S/k=,tag:LTy01pf1eMOtn/ltncYjOw==,type:str]
    version: 3.13.1
