# yaml-language-server: $schema=https://json.schemastore.org/kubernetes-secret
apiVersion: v1
kind: Secret
metadata:
    name: agent-sandbox-scratch-git-secret
stringData:
    SCRATCH_GIT_TOKEN: ENC[AES256_GCM,data:mSVKPyczwSq2QusE50OdvNJvnMrRj2zLjMssgTbT67W8uWxyZTWkRzw9JlOCcNW/vPLYS7aMUxz7e9U2O1wUSeOMzsAz/MU7eeLvmBN0GO3EU/6HHfp1931xfrQn,iv:OtR5PdWOx7GMyYzXieZlJiaehJuM4s7mfgiI/zKSW1Q=,tag:7pCgbS6qlLcC6p+pegYKBA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZmsxS3dQaytXWkMzRm51
            VVJZbkVMSTl0cGI2N1A0V1Nmd2I4SVBUbm5VCnczWEZJUklBcFltVHNaeEZ1c0Iy
            eVlCNG9lY200YlRYcklrNGxIaEJMY1UKLS0tIDd4STVncmV4QVlJdGRZZ2ROTXpV
            aHZXSW11S1RxWWNQZldBZTVhOVByRHMKUU0HZVz1iKWi1MsqR94ZYYZkTvBQv5Bx
            +xMpU2YjXNySJ8I29ZiexZYX1Hv1CWz8vAQO/HmzcGT/vwRcQ0tRUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T16:54:44Z"
    mac: ENC[AES256_GCM,data:eXqW+QIr6WouDohETEcECtEhLTQtsM9uC0Y3wYnvuqpWaaZMlpn90DqiWc4r/3OjdlHeu7qkrqJxWxMj7bHyRfUJdf23S9RYXByti7d5diEy5uK32uCTXFTRFF/bYtOA1yg5JDIs5ZOcme2boF5meliWZdHPCwk6e46SxGWO6CE=,iv:YomG1MxFEVTiHRwGOhteCnkzYxhqSGTweD8XZZ5jb70=,tag:s7KJF+AMyOwjj8h+1ATj3A==,type:str]
    version: 3.13.1
