---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: goflow2-rules
spec:
  groups:
    - name: goflow2.rules
      rules:
        - alert: Goflow2CollectorDown
          expr: |-
            up{job="goflow2"} == 0
          for: 5m
          annotations:
            summary: >-
              goflow2 NetFlow collector is not being scraped
          labels:
            severity: critical

        - alert: Goflow2ExporterSilent
          expr: |-
            increase(goflow2_flow_traffic_packets_total[15m]) == 0
          for: 15m
          annotations:
            summary: >-
              No NetFlow packets received from {{ $labels.remote_ip }} in the last 15m
          labels:
            severity: warning

        - alert: Goflow2HighProcessingDelay
          expr: |-
            goflow2_flow_process_nf_delay_seconds{quantile="0.99"} > 300
          for: 15m
          annotations:
            summary: >-
              NetFlow processing delay (p99) from {{ $labels.router }} is over 5 minutes ({{ $value | printf "%.0f" }}s)
          labels:
            severity: warning
