apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-admin-secret
stringData:
    API_KEY: ENC[AES256_GCM,data:oEHNIzHZ7mUEMszNlIKTCoKn7a7tFUNtk2XzCXcuJY4=,iv:TDVmgJd2CcQSvonVEBDQsgUZgysQJwOgiE2cmJqfjQ4=,tag:euuUGPOdEbq3ymQ7I53GAw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtYzdmcTYyUDVCQWpaZjk3
            amQ0UUFZMG5GcE1uRFJzTUZIZ1BUZzd0ZGpjClRhK05CZWNzdWJtcGZ1S1JOZTVI
            RU1zS3hWNEMvZTdCTU1QdklSb1pMQ2sKLS0tIC9hNzFMeWgvTG5OeVhxWllJUzZ4
            V2s4cm9hYjdmVkU3SlVvbVlpOXUzYk0KBGARXefjFH1aeYuX5jdO3R5lftuDcs+/
            xveuZ6tgQSeHrM6bcsZq/WVDwSy2XXsyMJbW3i666I/GlgEQmnzMgA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T21:27:18Z"
    mac: ENC[AES256_GCM,data:dac2eKD+sSxllWblhriP8Aee7rtc4Z/Z3UPNOGhFFrNDhGd+A3oFtcVb/4506zw1QUH15Recab6AkG1iwQDjX6P4vb11JZ/JxnEHS4EKP3H6kj5bOYYDoSNHI14Yhrdam+KYLpnpFuhdMJPiMgbT/gFnTlACThMnJNPtXLj0yaU=,iv:YAEsozkz4JlEFqNrS4cgNhY9saeRfQYnse9QbWd8Ng0=,tag:5gqA9r0WRm7VJq+gYAEhHQ==,type:str]
    version: 3.13.1
