apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-exporter-secret
stringData:
    JELLYFIN_TOKEN: ENC[AES256_GCM,data:0Roq5MV3W+atwHB2cBbtjo8RZG+TDwBzx2dFsLTN/30=,iv:NyZ9KOkWrf5R/cPiY27xk88P8IWCO6aRJVTrPYEYnTs=,tag:hSl9XfgH1tfJRXSv1irQkw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSlBVSG9pVnVjZjFOSkYr
            ajloaVFzZUMydEVkcjJGU0VjSktJN0dLNVdJCnNXUWFOUzZndnJ0RjZSV0VLQnoz
            amNIY0JNNzREeGttNTMxUkl3SUoycU0KLS0tIEMrZUdZenh5NmE0NENVaGZlRXVV
            bXNqb054SjdiMXlmZ0Y4bW16UTYwUWMKSfCsY9xhd2DoEfKUg2SyMq6oBxDC25+U
            M7L0/MZ4bvyjhWCTpx9ExquLwbYS7PWMlZn7wU0GAQj7CeVYvklIjA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T05:05:30Z"
    mac: ENC[AES256_GCM,data:RLGlBqQ19EuN0nyZQagkMvaObPXwYbvUdgfIzuCFq55lTstqQR8Q2OMXPPFUnkFS4JcVOUQqMcZXZcEEM+8Hfi0dpM3Foy66R0RpSN7VeJW620HQwCGxm4EwXQ1ijs+K0ZURrA2piK/+mD7eXHteVMQ/CQctgCnaRjSy5fmUhV8=,iv:mLIMLKsY0UltTfUORc3Vq9pwBS4bGm3iB/p2ZoOtHdE=,tag:SGdZUfopfCTPpdD8r+ezsA==,type:str]
    version: 3.13.3
