---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./exporter-secret.yaml
  - ./servicemonitor.yaml
  - ./dashboard.yaml
  - ./backendtrafficpolicy-metrics-block.yaml
  - ./oidc-secret.yaml
  - ./admin-secret.yaml