# yaml-language-server: $schema=https://json.schemastore.org/kubernetes-secret
apiVersion: v1
kind: Secret
metadata:
    name: openhands-secret
stringData:
    LLM_API_KEY: ENC[AES256_GCM,data:rxdXlz7tpMSa3Ek0DThjVo84HzQhNMZNPSW1a7QzOCbUPKS0qWbns8zeNEQE3K6sEjhs6K5Q3+9m9FSPmVC9z6ULt5ki8SHI9M34Liqq2v5Dw9DnT7/pfN/pbHN0qybPL6angGkKcTFYPd9H,iv:xiVv1Uyat5wWVwj0/xz7BtPRWhLKpknLblSkehkJt10=,tag:nFbwFu8ySq6CPOkL1xiSyQ==,type:str]
    SCRATCH_GIT_TOKEN: ENC[AES256_GCM,data:GP2qvV58gZ4hO8YCIzmhJHO+fQQsI6dBuGu/KFRPMZTvb8ors4OQHYGxb56LHE27MK8OgOd3f5YWQ6an5ILB3DLIjSZ4sXHGlcAhtb/oC8QvCf/mlAjrNHsDhfyj,iv:sFKGyY4jKk32EWFkg/9e+JSUBWnIWRvIhq6fzxIXP5U=,tag:o6hFgYrDM2u98yF07QCKVg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXb1F5S2FkeGhOVXdVWkhZ
            OGNDekxVR1BVSUplOHFFNlhxRDJIc0JIdmtVCkNqdFdTOU40UWJEZ244TEZsMXJH
            QkFHa1pWQnFraGxqcjRqU1VPbHRmd1EKLS0tIDkxdVJ4SWxUYzE4T2dUQStPYjlu
            VWpwMndkU1JwU0Zzc25DeHFiRFVrTUkK3t1W5aU4Ld7KWmjDMshPr95v7DQJPXGl
            Yx+B5j7SSIlKxQ5zDbJ5ZD4fVBQn6MOeZge+NjN7PBTQW9xKY5QCTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T16:54:52Z"
    mac: ENC[AES256_GCM,data:+c/t32LZL65eaqf7gtO3WJIqKnxcf8egUNdIQsrCOBplNpg2nhMXEQy2J3yoA6A8WZ81PhCbq1wKRO/CRjlOwfS+74FApG/fwg2XkLuEr0cboj7nPpb664/do+0AY9skhF/3wLQwKnE3RG1RRv81O5repg0c771qd/dUcF2Mp/I=,iv:75LnZN0/R3VGW6ab4te+cp2ox0/mlLSRUxSuJ4johe4=,tag:wf5ctWuAtpLQQhgwHCdl3g==,type:str]
    version: 3.13.1
