apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secret
data:
    RADARR_APIKEY: ENC[AES256_GCM,data:MMTTWPVaNltOfM1KtGSE2IADG5s/VdmL5cJY7WrgTj2RkGNKuQDg82kg6Hc=,iv:yjUtfT/lkxAeIJGrCQNnCYs6XtvPL2uTCGyZh3yqFaE=,tag:KAgkT88ZbCduiEvAZLNAEA==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:L4XAeRrsRz5MjVO4qL6D9+i3l7LrnwklEe/Yg1wb3Wa7Qi8EQRQLUdZvbkg=,iv:Y+JztEp4bdZUppJYw4b8wdGCUY6S6P3A0GgXr6pcBX8=,tag:Qsg7jsDlMlbySYPBZvM5aA==,type:str]
sops:
    age:
        - recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWVc3cnVCRzIwNEdiZkpp
            SzRvK1lsdWxMaHdjYW5zYzYyUmtpSWsxc2gwCjZVaW5rWDJzOVpMVlZ3ZGxmNVpG
            VFlMeFEwbm42dnUyeFp2WkxJWGZpR3MKLS0tIE50WVR2c1VLMGFPTEJCWmJPUW1H
            bGpVOUN1OGYrQkt1a0RVT25EL2IzY2MKthq0MpB/47ck7TJ+EfF5/WZsyOniGTjx
            wvtPiCdNy0lwwF2EnFqHkW4nI8YOYWoz7b5UbqMWgHFl/UVjVhFDtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-26T19:28:14Z"
    mac: ENC[AES256_GCM,data:rk65t5RmKDfUkb1r/6rh8VbKNbuEzrUAWxpogVpkjma64ahB7bcQEb+S++605DEfs3wsROmI1QcrtpbPT06s4CbANbkAcjiQgLufsocZ5kIGnmjl2LUaBc9WXtw15oa+FmRgSCE9no4V90MoHvrIglhyJMa9IzqqMmC8H92kXqI=,iv:h92lKAPV3P3VmydXP08u2r4r3jSdzKH7AToxgqIWJMs=,tag:eDnVunZLPAj5g/OZb35kSA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
