apiVersion: v1
kind: Secret
metadata:
    name: audiobookshelf-admin-secret
stringData:
    ADMIN_USERNAME: ENC[AES256_GCM,data:W/jN+A==,iv:ExikATh2pfXKBKAUkwawjYpd8DPL50VdrsFP0P6YlW8=,tag:aoB3oCd46cOx2T90AcZlKw==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:QcsyMJCOYg+SeHoapt5az5qq9iuXMxwW,iv:8U4j+CJxDRDsSdnDC6gVutjKOaLltmURm589IrDR3Yk=,tag:lY7IW3TXODVIQKyiraehfA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSVh3OFhyUHpETDAxMmUw
            RUJNN2JCVW10U3JENTMrZ2xJWUswcnVUYzN3CklxVlcwVGFEcHZFaFVnc0VzSi9a
            THBuaHB6YU1ER0s4TVJHWC9BWXNkKzQKLS0tIGJ4V2pXWkpsdGp2QUNsVWsvYk9J
            QmQzTUk0WDhwZUNQMFBZbWUwYWtnN00KhgEXbz+5P4TyyLi7ZXZgzUXdcaoEIZrU
            +4NtV8KB9W2Z38uDDJSI1rBLiBNUrW1LoU1Y5rljCUa6a2rpvsVMmA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T16:35:34Z"
    mac: ENC[AES256_GCM,data:noyD/C74RJCgbpxSUfPMlreOoMNLNPa5Yr2ap9LzmCXBx5oHYbQutEqj+H+IZX2U9QqWiNx0mbUVKfxDiX4DX34zqgLqnN5tbN6MoUJ/T4l/rj8eO3L4g/atSN4KO1qyeM4nHMFj/XtyGqczoPopM80jcr3cjCnLKaJcI5QZsg0=,iv:TjiLbmzya6fIlKPAZDPQisbEmQbYd0Kw7Q/TCS1PQGA=,tag:BD2J/LxPb1ACSLwf3JnwgA==,type:str]
    version: 3.13.3
