apiVersion: v1
kind: Secret
metadata:
    name: radarr-secret
data:
    RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:FL+vuTFQQu6drTuWbsdpr8WSFceh1LBh+sT4NRBsUvVRfMOYwJ7XVtas0fA=,iv:7P9KqnxLs/m8CCf9qKeVLA13xTyvXzczi/1UcPRqRqU=,tag:ImQIEgLEFJgdgo0zLxwEQQ==,type:str]
sops:
    age:
        - recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bXY5SHRpK2g2Q1J5bzNq
            N2ptQXloT29wK2JwWUR0MXhKbDVTYUZ4NWo4CnJ4THdYZzRKZnhHazJzcHNsUjZ5
            SVVBMnprUUUrUWRReFZITVF5bEs0RVkKLS0tIDZKaUxFRitFQ1JzRjlreUZiR3R3
            S1Vmc2ZaWStUVUQzKzhYZmNhS1BCM1UKxQPFBNMigLPFBxmSwxXfN5e182qA2yXF
            UlCku9AGBm7I14C+cDNyNZ/V7ffbJP/9CpCvv3UpL7Ox02yW46iAAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-26T19:26:11Z"
    mac: ENC[AES256_GCM,data:dL1wjyRcwdgYnZVcaEKFwMCTB3HEDxfqu576FtBfwGNq4Pj3lP0C1ANAzrH7pA7pWo6hzuyzm3IoZNvazlxgNKyjZN7M7g6lXd//AXecOHfr3UewFg+m62LHquG1rZ2jO90+faw2nMmpIl97uici1h3hJbbaR4vU6oc7URMpV+Q=,iv:gBJ0I3N8JECVcFsn2JTkyxBKHy3ZfhEeKTPpS8s+kh0=,tag:XhFnc7L9vMmZZRjHy2kaiw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
