---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/k8s.mariadb.com/mariadb_v1alpha1.json
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: grimmory-mariadb
spec:
  rootPasswordSecretKeyRef:
    name: grimmory-mariadb-root
    key: password
    generate: true

  username: grimmory
  passwordSecretKeyRef:
    name: grimmory-mariadb
    key: password
    generate: true
  database: grimmory

  port: 3306

  startupProbe:
    failureThreshold: 30
    periodSeconds: 10
    initialDelaySeconds: 20

  storage:
    size: 10Gi
    storageClassName: ceph-block

  service:
    type: ClusterIP

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=512M
    max_allowed_packet=256M

  resources:
    requests:
      cpu: 300m
      memory: 256Mi
    limits:
      memory: 1Gi

  metrics:
    enabled: true
