---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app echo
  namespace: &namespace network
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/authentik/protect
    - ../../../../components/authentik/protect-external
  interval: 1h
  path: ./kubernetes/apps/network/echo/app
  postBuild:
    substitute:
      APP: echo
      HTTPROUTE_NAME: echo
      HOSTNAME: echo.internal.oreillys.io
      AUTH_HOSTNAME: auth.internal.oreillys.io
      EXTERNAL_HTTPROUTE_NAME: echo-external
      EXTERNAL_HOSTNAME: echo.oreillys.io
      OIDC_CLIENT_ID: fbfc835d9e156b3410fbec77da601be1f0af24e0
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
