---
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

metrics: true

storage:
  type: sqlite
  caching: true
  path: /config/gatus.db

ui:
  title: Status
  header: Status
  link: https://github.com/brianporeilly
  buttons:
    - name: Github
      link: https://github.com/brianporeilly
    - name: Homelab
      link: https://github.com/brianporeilly/home-ops

web:
  port: ${GATUS_WEB_PORT}
