# sops --encrypt --in-place oidc-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: grafana-oidc-secret
stringData:
    #ENC[AES256_GCM,data:8DBdynduMfT4IexgG4grf7cPbVAWVqxXy2xEdN4WmCec7qWaloB6b1+EOSJVDVFNkjjKKpEwVINEFzSuU845z2B2NfDJeyBkvzHdh4Xkbas09eeWYw==,iv:hIqpman95pWRG0WVyBV/RJxVfEepCLQKBpC3h2rp6gE=,tag:Av1n0fMLfYjsVzgosEJPiw==,type:comment]
    #ENC[AES256_GCM,data:UCVRvktYu/LKY29Cq5HK4hKXB4JTOF7llnNUMojeoWHCvscrNizIAvTetYAXolIOsoYP7EWhZ7k9ZvAYatXpbRrOCNdi9g==,iv:34uVy10C3DyYhM0bRHMrDOdM2aP7tLEIY7my6aY6ZvY=,tag:elzO0/pMRLSsLgeO8ussqg==,type:comment]
    #ENC[AES256_GCM,data:IC44mwN2J9LXKzsshQue7QnBcPze921NyayY0VwMPACHtpCZ6gpo3D7yGSp8MHVy8IjQY2pYWR7CUT5CYvjNlsfiWKsM,iv:MqyMVKWdzfQJaQA657ihXqn/ya5RVQmJ7Zg5U6KuQWE=,tag:aiMZZwH8DW2zwqSfDeGT4Q==,type:comment]
    #ENC[AES256_GCM,data:khjmbNr+KQ1WYCN5Yh6V2Fuxjd79yyUGUu2zFALkWMmvC2Ns4oxysw85KPRAmctHQIgl3sIWc3dyVLMQInX4igo=,iv:d0G1/Vsj2RhgjDL0ElTZzp+EP1Gof8K5P+cXwCqUC/k=,tag:hDiAcvkvPVqJO9vE6FCqVg==,type:comment]
    #ENC[AES256_GCM,data:r9o9pv5gngdhwe2Kz7HkjrAkL6IRgO1q66reGrq955ibO8x37TfccBGA,iv:Tm1m+kWumFiwzeArIuTNxlz/J22xX3NyJL0XmakS3a4=,tag:RMOy3VhLQ9hCCX/JgyC8ZQ==,type:comment]
    client-secret: ENC[AES256_GCM,data:S4AQEgNepueE2BQE5+uZDV0RGYN3rugEibhAY8BiY2KZCfLraw6kV9/8gKauQGsE2zu+M8pYrNwtBn81VFE7DWDWCB6aFXVpvALrDENqV7A=,iv:+zj3fByTgBNhcz/YuM83Q8rfX4mNrx7EtWRiKxRd758=,tag:Ja7BOhZcRglADYT9Pmk5FA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIaFcwT0JuQTZWRloyS1F3
            dmc5VUdWTXVPUU1iLzdqaThveitHQ3F6QUVnCkN2aGtsczg4M20xaW1sQ2RZdXZR
            YzhLelo3VFFmMy9sdkpZU0NhWlRzRTgKLS0tICtHVlZyYmxZSS9BYzRmTXJ2aWpm
            QUlnaStXNnJvcGNibFNqaGVta0t1SFkKOPIrkQqQyy/ULbJJ5UnEm6NT81RCMCwo
            PQtgcicW1YepmteFrT8QxLlPp5lptFOiesZFwyOdgXx8OokcCojCZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T17:56:21Z"
    mac: ENC[AES256_GCM,data:Ylxusx+OMBVWJZcGXX7DsETEzxVc4WJ91humqW+HHs4PJ2FrkM44XaRFK61+qNUr7dBwBflSocYGFtNhvNQsZoElCSrQnEvvdOJ4I1/G6DpBUKLM/ZzSPfB5CXBPQf3cwoZJjQX9jzibP/1lPArZmjsyzFRlpmSc3AHtrZKOtrw=,iv:C06ftexTu7tup30ZbWsC9KGJPX6Y2vWM+ZnvmZHmM1A=,tag:tT9ipi7M9/e4P5rXpQM9qQ==,type:str]
    version: 3.13.1
