# sops --encrypt secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:2w/ul8/0uXzjola978OqbZP1fIOdlivLDruRaYJmS1MAJnbVBq0MaUn6ggIZJ2YhnbaKPLwdQ4JOISkRjSs8birp5f4E5H69r8+NjT/vHGY+sconQ4kIj+o7pvfF5NUUPvOxZA==,iv:6PmfaJ2/Y65ex01QcYgTLCmYPqJ7CB4ietVUh/dDMh0=,tag:Nnr3aZmdz1wJTgCemgKeBw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbFl3d2hjeUdKV1lSUzFh
            djJpcnlqeG5EUzhUWFhJNElXcmxKYU1wUlNRCkpWTmxpcXZtM1h2RzVxS3EyTUY0
            ZXZSMm1ZUFg0TEs5ekhMU2FJd2pBOTQKLS0tIEZ6UFpUanJpZWVQZGx0K0JnQ1l5
            WUpMSVdJd3IrL1Z4OTdNSzdra1UwZGcKmVuIdMMdlnJlLdlFiuiyZtQKy25NRZFR
            QuIoCrTqgDw8fDP/XxqlPNXiBbpWrnp7l/riS1vNi3kwIqI0LFjWug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T23:14:59Z"
    mac: ENC[AES256_GCM,data:qF+YuytqHm0K6U2rHQZVQCOzo/lgS0+Gm7odVQEkp9IFmssAMOdKr3+RgquibKN8vBeSFIyW2TqbA0bWO/I3KiFcVfPrYKGUXeI6q722HHMj25gqORmjbj90w7hATE9MOCxTJeKWTxziCEEtgrWcpsPU68bjAFTTebSFFhMRKSE=,iv:SLUvIJxtBFIqugNwrA2J3LB8FR8UcFN0/fo3CMiuKf0=,tag:wvn6jIh2zxa5qfkDFw8a8A==,type:str]
    version: 3.13.1
