# sops --encrypt secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: crowdsec-secret
stringData:
    #ENC[AES256_GCM,data:32+S+MCGoRaKOMr3c461aBXRxvKPQNrib6Py663EEHi78UNAcKtBRJwcm65XCDXr/20lD24PLMzqTuPB2VKt95jxlDU=,iv:8zxft0EYcEl8W8SoZTcaCN8zVBKbloiXc109RcVx6Bs=,tag:IFKKczVVWn12m5pxSBvnIA==,type:comment]
    #ENC[AES256_GCM,data:PeJDFncvuGJoBjbcxxJhH4tNdfPVb0ClmINCIUwtsE3BjrH8qSt7tQGOqYZ3mGDON5w/YNE7XaO1QfNpZRJ5TNo=,iv:MdtPuyFsxNhbx1HgWry2bHKM1mlkENq+WBiHpYndm4E=,tag:RM2W+A48x2fyvyPhSVSaAg==,type:comment]
    #ENC[AES256_GCM,data:YhSvt4FQSXcdQixQ57k7vasBJkMjPSKmj95hBBbt7pvH6rLakZrpf7kYGs2vhTuGm/inPDuevDKjT2pzMbON,iv:zKVHYjlpZ0jdHI7WvcOYsxPyaF4NZhaQrwl6ju6z8C4=,tag:V/J5R3pfZfePNf0WK/CwMg==,type:comment]
    #ENC[AES256_GCM,data:Qh19iQMyHhnc6qgAONDzEsyAXasP2eiWUFDhvanriN3Jtcw/zHCgXswz4n6lU3yIsmbPet7LvAgtpn7tjjtbVenAxw==,iv:ozcSTyRmIl1ExtETazGFWDOYlSEw2DB7H/MGjchZvQU=,tag:qsMsEI/4kuLCoQSP7ukoPw==,type:comment]
    AGENT_USERNAME: ENC[AES256_GCM,data:SlZ8NT2Rv+htv31NWBeoyO+0CqF8XyE=,iv:bZW1oZysHHsI2Ne13WTvTosRyMR284arOt+L9j7AweY=,tag:5K9VmFICerMIEukaus1GTw==,type:str]
    AGENT_PASSWORD: ENC[AES256_GCM,data:Pms6bD2IyGIghAd5EzdvarbaY0UAOdmJW/KnV9w5EQc=,iv:s4Tly/LwlV3QXuNxn6mUijQjERQ6FWwI02U25VKSl/c=,tag:qiZkXFobovNbMN7XQM5Iag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NEwwa3hCRko3V2doT0pz
            WDJoUXFyNk10cmtSMlRZUVl2M09xR09DWEd3ClhTbmJkbU53UnJQTmxzMitIaE04
            MjVBQUoxa0ZtZDA2Z0kvdHdDOFJGNmcKLS0tIHF4azFIYzlEcVh5ZVVYejVFMzhM
            bWhlaFc4WnNuRU4vN3VsSWlYTGY2Q3MKiDIOIbbeZTuPNdbySH7P+bEJrG3/+BK/
            8bYfYlCHO8K9tue9CUzAteJOKz3jugt6cTVCk0gqcULcnBnPvoBM2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T19:12:54Z"
    mac: ENC[AES256_GCM,data:bJx67LUqml4skG9Fph8vIFiY5J/6M0kHx+jBX0TFziD8K+hOF6x6tCLKHdIdb5U26XEyvub+r1Z8IeMN9ZPMjBc598mT7y8f6e5HkUzitk4oIB9mdNmnKKbuyyIjFWHAiY3JMQbA/ONo5wnowYNvxCMiV3mJk7d1d2bjiIE1yj0=,iv:PxtL7i92JpT96xxs4xuK6aylf0/y8urZ2QEouN1g/Xc=,tag:0KOjLCAs0ThJIiA5EssB8Q==,type:str]
    version: 3.13.1
