---
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: akvorado-clickhouse
spec:
  configuration:
    clusters:
      - name: akvorado
        layout:
          shardsCount: 1
          replicasCount: 1
    users:
      akvorado/password:
        valueFrom:
          secretKeyRef:
            name: akvorado-creds
            key: CLICKHOUSE_PASSWORD
      akvorado/networks/ip: "::/0"
      akvorado/profile: default
  templates:
    podTemplates:
      - name: akvorado-clickhouse
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:26.3@sha256:e8190631df42b9ed461190b46c628ab476e4809ddac207e609d59eb44e20b209
              resources:
                requests:
                  cpu: 500m
                  memory: 1Gi
                limits:
                  memory: 4Gi
    volumeClaimTemplates:
      - name: akvorado-clickhouse-storage
        spec:
          storageClassName: ceph-block
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
  defaults:
    templates:
      podTemplate: akvorado-clickhouse
      dataVolumeClaimTemplate: akvorado-clickhouse-storage
