{
 "title": "Akvorado Inlet",
 "tags": [ "akvorado" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "UDP: packets received",
   "type": "timeseries",
   "description": "Number of received UDP packets per second per exporter. Each exporter should appear here.",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(akvorado_inlet_flow_input_udp_packets_total[$__rate_interval])",
     "legendFormat": "{{exporter}}"
    }
   ]
  },
  {
   "title": "Inlet: flow errors",
   "type": "timeseries",
   "description": "Errors from inlet component when processing received flows. Some errors are OK during start, but then they should disappear. Errors include decoding errors, SNMP errors, and processing errors.",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(akvorado_inlet_core_flows_errors_total[$__rate_interval])",
     "legendFormat": "{{exporter}}: {{error}}"
    },
    {
     "expr": "rate(akvorado_inlet_flow_decoder_netflow_errors_total[$__rate_interval])",
     "legendFormat": "{{exporter}}: {{error}}"
    },
    {
     "expr": "rate(akvorado_inlet_flow_decoder_sflow_errors_total[$__rate_interval])",
     "legendFormat": "{{exporter}}: {{error}}"
    },
    {
     "expr": "rate(akvorado_inlet_metadata_provider_snmp_poller_error_requests_total[$__rate_interval])",
     "legendFormat": "{{exporter}}: {{error}}"
    }
   ]
  },
  {
   "title": "UDP: packets dropped (in)",
   "type": "stat",
   "description": "Number of dropped packets because workers were too busy to handle them. This should always be 0. Otherwise, increase the number of workers or the listening queue.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(akvorado_inlet_flow_input_udp_in_dropped_packets_total[$__rate_interval]) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UDP: packets dropped (out)",
   "type": "stat",
   "description": "Number of dropped packets because internal queue was full. This should be 0. Either increase the internal queue or add more core workers.",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(akvorado_inlet_flow_input_udp_out_dropped_packets_total[$__rate_interval]) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inlet: decoded packets",
   "type": "stat",
   "description": "The number of decoded packets, by flow type.",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(akvorado_inlet_flow_decoder_flows_total[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Inlet: forwarded flows",
   "type": "stat",
   "description": "The number of flows forwarded to Kafka.",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(akvorado_inlet_core_forwarded_flows_total[$__rate_interval]))",
     "legendFormat": "Forwarded"
    }
   ]
  }
 ]
}