---
apiVersion: v1
kind: Secret
metadata:
  name: akvorado-config
stringData:
  akvorado.yaml: |
    ---
    kafka:
      topic: flows
      brokers:
        - redpanda.data.svc.cluster.local:9092
      topic-configuration:
        num-partitions: 8
        replication-factor: 1
        config-entries:
          segment.bytes: 1073741824
          retention.ms: 86400000
          cleanup.policy: delete
          compression.type: producer

    geoip:
      optional: true
      asn-database:
        - /usr/share/GeoIP/GeoLite2-ASN.mmdb
      geo-database:
        - /usr/share/GeoIP/GeoLite2-Country.mmdb

    clickhousedb:
      servers:
        - akvorado-clickhouse.observability.svc.cluster.local:9000
      username: akvorado
      database: akvorado

    clickhouse:
      orchestrator-url: http://akvorado-orchestrator:8080

    inlet: !include "inlet.yaml"
    outlet: !include "outlet.yaml"
    console: !include "console.yaml"
  inlet.yaml: |
    ---
    flow:
      inputs:
        - type: udp
          decoder: netflow
          listen: :2055
          workers: 2
          receive-buffer: 212992
        - type: udp
          decoder: netflow
          listen: :4739
          workers: 2
          receive-buffer: 212992
        - type: udp
          decoder: sflow
          listen: :6343
          workers: 2
          receive-buffer: 212992
  outlet.yaml: |
    ---
    metadata:
      providers:
        - type: snmp
          credentials:
            10.2.0.1/32:
              communities: "REPLACE_WITH_OPNSENSE_SNMP_COMMUNITY"
            10.10.0.1/32:
              communities: "REPLACE_WITH_MIKROTIK_SNMP_COMMUNITY"
  console.yaml: |
    ---
    {}
---
apiVersion: v1
kind: Secret
metadata:
  name: akvorado-creds
stringData:
  CLICKHOUSE_PASSWORD: "REPLACE_WITH_GENERATED_PASSWORD"
  GEOIPUPDATE_ACCOUNT_ID: "REPLACE_WITH_MAXMIND_ACCOUNT_ID"
  GEOIPUPDATE_LICENSE_KEY: "REPLACE_WITH_MAXMIND_LICENSE_KEY"
