apiVersion: v1
kind: Secret
metadata:
    name: akvorado-config
stringData:
    akvorado.yaml: ENC[AES256_GCM,data:9TG2IGv60ziFw9vA5rcitblD9cfNgBpFvJlDsyIOhX/WarEGW2zfQl9t7KStT6qiWqYyCHT7aijhixcFqZzV1nNw1OP3bxwPBo9uKaGSHcrMjlwTYyBsMYBvLrikdaTkv41E6GF6WdG2AvqjkgDYkoOUDXF7+ClywHmD9VYtcUpNQtwuGyD+mhL+M0Tc9QGBDQ+mA333CWimq9pEdXAfX+XcL3jOT48Ft2/+MD1Dpz2inXMGjFpV/hCUfdmnoSfdmzM6ebyxJdk/MwhbfyOWVcqYGLG6rT+TOUr5qm0F0iseCAVnj74bYE7iWDKGu5bgGkUIwZMH3eUzxd5Tf1PX12TkqD5FqGRkZjhkGY8cuj15VBr8v9uKsqbdpU+Pv03Fd3BQuG/2neA4x0huMWd2G+1M0xDnclp5dQAkpYQPiF1HOPw40Qd2nCpSqfyM2lYpwQYUJX6/dNaZA8wvK40sdMShA/k7b+GFEl7W4cRApoJw9IpNF8ZIO0ZHfTnIXJltjnuAP9ZEhraSA7ebuStcJaHE8SQ56h6OKDEh+sbx0AutsNJ4sJ0tx+fLEqBNSH5EO2rRUSjdWAqsta+akhJ0xi6Axyta7ek9rBaHzfZm2yrbaQ5Qbq/OpLTioyF5wmu6mGdFdTjan0+KaGoOaqzaLNZPq7/XarnAXNsfBtQ+wUa0Lp2RZY5JDYHhL5vxTUfqF3nhd8rQ/CuM3i/vWe/+JNrhA8vNu6k1t+uTvF6issg84MpN8lPI3fx7+Juh4kVBFkUrNRBjTo+2ZuGbYQkKe1Vm93/h+qXLDn4hv+jjXhnKugS0/asQfH0Ppqj8NfinDkNkaLEzBI+kxsDRkvtcJxXb7k3l4zJ9vkRs/jR20RLbVVFbAf6sfU3baRHEg2yXOLGGEXV5CvaPiWpC99YCQyUB0TTuic9gJ8njSwN4ndvGDuOS/4OI4WXLLxEW1c3h1WVwydq2Y3/4TV9vfkBFi0raOHE=,iv:IrIEjpeUjbJZpVwwn8B5ktQyLfMZm6M3p5PK8Xib3ns=,tag:XSql2wVIj3C7tcZxD3YgcA==,type:str]
    inlet.yaml: ENC[AES256_GCM,data:QSnqg4TCdMbiastHm8k6Q2zGiKn65OXLKBsanSCi6KzXoVLMerFdQxagM7dmGGVK08S43ftJrBb3QXAk80vU/Jz19VY713QXqDXkZzamnLcPg10e+uCVN67VDnsLAdtIK5Qhc0Cxo3IYXZxVbdEtl3r3oSzEblR1HfAW3XzHOtULP10e8KXPCdu26igOT9FRSLKmAeeR7jDyvZMte5pdq9W9gC6Yz1QqcuCXasCPPEyAuWIuxmKcvVTKzzcvCumvGhSy8fD7d6WuMFnrrvcP4NRq+SnxP1omADaVZ/MW0XfdHxknxsaZRFnPAjNJn8LBQHG1Gj7Hv+U/Bnka+0WeaTLSJlNlNXYrZp/JLGKnBeii9YeBPe95VHqAkbIexg5WRUanMauvEnxjukpIqRC8Rf/dEDQ0LrNMFADXbt1l1ySmeosfMDVuFjeobnii,iv:b6cHtz4AKJtvigEaEZTlSmLxmG8xKZCtS3qTQMnMDl4=,tag:wSyC9Fu29jUJ5Uk/KdwCOA==,type:str]
    outlet.yaml: ENC[AES256_GCM,data:UMKcac3xe7IQhJU+EwUHx1GRH51kWSY9sj93boqQ/HsQJmQ8MfXhCfa8ckvJjVBOZuqpdYjUcMYe15uJMMWsKKu5dFpIoVd/+MmijC3wZoFH1aNY36zCtV1mPNH5ihXu28Zx0q5qGGc3ng/PARY32E4PIhdbFW2Pe0nPsupAuo959rbLfbdHpoDxX3jMgxAs4pKUCOYW2SEW+UGtD8Jjwkw+WIm9JryxYwR0+VNGX0UKHtZBLTEDe+MMa8zwIZ/hpPthGgpJ3OiXa9Yjqj7/KcWtO5MI9iSaiBUL1qT5Qmukv2nrAEYCYfM/e1abmFuulBqKPGVGBpB7QSocm/SFsF5wAdSTC/QHc9TSoFVq/tOAFqBb+EcpPZKcbcQwNVho9vSt4anWOtGGszyc4I/nuFT64x6aKnyOpkNbiMAshKC668NIdspIj1XzPEq5J11rfI7sZabD0MRtIJuafYdZnDzjymK1fITFAGMAdL6hyBGElxGcmCUirPBzWR8DNVvSWy9O3k7qTK68Y0Pz0Db8MwM0O3cEm6j6LA==,iv:cjS1ZXrhe/CcwNpALc850Xfj02vPaljJiEIA5hcHRx8=,tag:TjTlsiCTou5h8T443Xa8GA==,type:str]
    console.yaml: ENC[AES256_GCM,data:00GEmtZ9ESBo4hIq1oBJRH9h7+8N0mdW9H86nA==,iv:LGmvMJPCQ57DUlqi7W7fICeHXwjkVOyq+IqVA6e9V/A=,tag:uCx5PzFFYioc6WmBnUA37g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWkRjRW41M3JCVnN6K3Fq
            cjdmTWZmRnNFY1pPQ045MXpmRXVsWXdvVG4wCldBNzZjYVRnNW5OQy8wdDM1V3dY
            dGRFL2Nsb0VzcUI5MGlod1ErSWh3Y1EKLS0tIDcyUS9jSEdmTTZEWTB2MSsvaHg2
            UklaNVpqMHBqcG1GcFhnaCswclArT0EKs7NhKGrzlCBP49NlEiKbGWbVQCFhx2rZ
            B3kYYMNCb7mJR08x3Evl3l7kyvcDfO3aAT40M8CiQndo03IAfsQ99A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T05:40:22Z"
    mac: ENC[AES256_GCM,data:caYn5PNnPEA+t1bxRJpocHGFgAhzVtF7ZFj3RIqFNvExY1SWbcjodq5qPbQwxv0yJKAZwqul5nb/lUrlKNGZ2Fkqq1dnfZ1S6zd9/bU035ZNJUk4176R4w6sKydFT5nNfBWp/Sjy5fSvPTiM3m03ZazqIC3i/7oUHHztTqj6KeA=,iv:JI87iOBHzohWtvjTv2ihpjk1JxjgYIdnmXoK42Vi7lo=,tag:CoO5RziKTkzxiw1EzDskvg==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: akvorado-creds
stringData:
    CLICKHOUSE_PASSWORD: ENC[AES256_GCM,data:OJF7hah6imiuOPOL42xFPIWGgEXBkmTDEMfkxBOtd5R4tsKq,iv:9NmedmwMnJ1SsI8GzRDGONK2suxY+qCXu1ALmOpsriA=,tag:vKSloOf/RGJ9Q+s7QP0WUw==,type:str]
    GEOIPUPDATE_ACCOUNT_ID: ENC[AES256_GCM,data:41w7NdpTng==,iv:hewmyGxcOYuRyqsxmDYl3AKTMnXOPGmLGhHAWfiONBY=,tag:7mj58s7Jr53m/aE/+CtHrQ==,type:str]
    GEOIPUPDATE_LICENSE_KEY: ENC[AES256_GCM,data:y34eMOL39LFzvCbOueF/IWXina70Mig4U96J3Lo12uHv0oQQNJRqCQ==,iv:cAXXbDCSRS9Ldt5smigv79Yy+XgxHFWcurHJHwGh42s=,tag:KzZDHuvNMUalx/jeUX6dkw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWkRjRW41M3JCVnN6K3Fq
            cjdmTWZmRnNFY1pPQ045MXpmRXVsWXdvVG4wCldBNzZjYVRnNW5OQy8wdDM1V3dY
            dGRFL2Nsb0VzcUI5MGlod1ErSWh3Y1EKLS0tIDcyUS9jSEdmTTZEWTB2MSsvaHg2
            UklaNVpqMHBqcG1GcFhnaCswclArT0EKs7NhKGrzlCBP49NlEiKbGWbVQCFhx2rZ
            B3kYYMNCb7mJR08x3Evl3l7kyvcDfO3aAT40M8CiQndo03IAfsQ99A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T05:40:22Z"
    mac: ENC[AES256_GCM,data:caYn5PNnPEA+t1bxRJpocHGFgAhzVtF7ZFj3RIqFNvExY1SWbcjodq5qPbQwxv0yJKAZwqul5nb/lUrlKNGZ2Fkqq1dnfZ1S6zd9/bU035ZNJUk4176R4w6sKydFT5nNfBWp/Sjy5fSvPTiM3m03ZazqIC3i/7oUHHztTqj6KeA=,iv:JI87iOBHzohWtvjTv2ihpjk1JxjgYIdnmXoK42Vi7lo=,tag:CoO5RziKTkzxiw1EzDskvg==,type:str]
    version: 3.13.1
