---
endpoints:
  - name: "${APP}"
    group: external
    url: "https://${APP}.oreillys.io/"
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 200"
