apiVersion: v1
kind: Secret
metadata:
    name: immich-oidc-admin-api-key
stringData:
    IMMICH_API_KEY: ENC[AES256_GCM,data:Pqh5WYhGBBrp8SJDdOUKiC6UyfY0jVeFXsCVNgpksV4PaBfYINWfduw=,iv:RwuaP21+7Yfxkuq8S5Sziegjyj6eCAyGCqkTQHpXRF8=,tag:aiWTyGAqBf/sswBj//RlbQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWFNOb21hMFRmaTFpK2xr
            NVBWRWN6ODZFU2xueFdKbTY0R2pLaXc3Y2g0Cm5rVm11T1EvT0IxTENINytuelhZ
            bGtzNDZSaGlrdFh4LzMyZ05UeVFwUjQKLS0tIEZzVThWTWlieFVBMExaTTNCTEtm
            SFFvSzl0OUJpV0tuWk9UOC8wRnFGQUEK4X418KQPL7JYyfLLFyqPBuie+rFxegjL
            qJzoYtnZgaHdR0QVHu4l8GzRIK68LswsQoHiQItExgQ6KoQo6oK+Gg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T06:33:26Z"
    mac: ENC[AES256_GCM,data:GfM2WtIfWLCt2UZ5pDaFB0SqUiPK9fdoa6qem+EEm1BgoEKt3xvFL+6wMDQKPustf7H0IAd+a9sxP1b9sTY7QMBLLbX6QN/um3jwAUB9/vGI04Kt39cfPuAJr2qUSeMNpdONE68HNesVbXB9qZTlbG9B3BR3LlpHLEHd5VpZ1oI=,iv:FkSa/rplMoLoveXDXKwES6v1IcSt/8uJnfQm7kBZfRA=,tag:hMtzwYiG4TMxoofdz6sxHQ==,type:str]
    version: 3.13.1
