apiVersion: v1
kind: Secret
metadata:
    name: tube-archivist-secret
stringData:
    #ENC[AES256_GCM,data:ceNwXrbrph+6qFwk8JgyvTJ7tjGa0tKBg6nVgZomyhqT58erex2GAfK0kPqOQmOauwOq2DIBZZARNSb2WFcQXS4zi2i99vbeHuExnG+ubw==,iv:I7SWJ6EOQ5QN2ELpDtwGX/wqW9afFWp1LPxpPVnYE3U=,tag:gvu1NmP33xikF0f8SbTHWQ==,type:comment]
    TA_PASSWORD: ENC[AES256_GCM,data:tmHJHROL+hz1fSicTqUTCn/7V5Eub2I=,iv:QKqfWZ/1x+KG1ZMsM3/R4To84LGEY7UZy8ePVWjS8gA=,tag:KfA7MMTipFz9OfqCYCKy8A==,type:str]
    #ENC[AES256_GCM,data:nSHjE+WArVvIr4lnwRho9WvsQiPxyXJB78CFEf1u3ufs31c4NhXTHnqqp+f5+Qer8AqdQ8pOD+iXdDa+GVGJ6j6nrGEvw6CwNg==,iv:PjWgT7t8BGUnrcToI3cIWGs4T9PO4Eu3z+xeFUFQgLU=,tag:AmTIji+5HWhPIbTMJP4nJA==,type:comment]
    ELASTIC_PASSWORD: ENC[AES256_GCM,data:ZeMY3ehIIwe6uF0gXwFXzGNWMqlkA4OZ/D/gxyZ9hzg=,iv:u15stz2HVvGVTWpi6TeDoDvSQrtq1sfwxBRWxisJjDs=,tag:HNzYTHuMfv7ejKzmxdgdPg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RGgxSDUrR2kvUDdQMHJL
            d3VHOUsrTTlCejQwVThBcU5ic2VUa25Sc3lrCm5waElYOUZybFNvMGFZNlNRT2wz
            RGdGbzdGNllQam0xb2ZOUHRKN1NnUGMKLS0tIEsyUjZHWEJtOXhmVFc1TVF4aEZX
            Q1pnQmxOUmttMlZMcmtON0NSeFYxV1kKtWAmx+kTYbEfQpyw9iNp0SOMiNZostST
            QCeWNmKgDrVNIh/CXA5L75RtJE6r9a3kn5K6bOZchi+xPSmjpvErBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T00:27:35Z"
    mac: ENC[AES256_GCM,data:BRzB8n9+RehGygYFtMnmEY3KHjL1juNlMWzhlvMJ0mPA0xk4MkaEjuIzkbO/H14QkSq6aNOJEZEW3S/0a7AsMyk+m5yGQOacS5bUArAAviN7fBbI2MVksFMFpd1dXxd1H6PjL6+2yjT5p4Lj+XGqGvsXgXH3YuUigBW8D7TeBOQ=,iv:KOe4RFn6IVw9QdTpetIxM2SsueyTpblRdZwH9WKWANI=,tag:OWDmIrwqUB4wsK71NbBLlg==,type:str]
    version: 3.13.1
