# sops --encrypt --in-place b2-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: b2-offsite-credentials
stringData:
    #ENC[AES256_GCM,data:a8a4v8OMENz4W6zk3aAUzsgmFmnMpJuFnKcPJMsE/QNVdGf/WmJe9OGTw09DHFKZ50fKE4IM6HuuJfvFLZP2V1VzCg==,iv:EAAOsxBlHttntbP7vI97OVYfa5/ZdVukOj8pE/TnJN0=,tag:Vpsou3Zpic9/piKLKff3HA==,type:comment]
    #ENC[AES256_GCM,data:xyzDhytfI6K5DYEDSTT7TdEXGvXtCWs212APOm8hKKf/8DFePi9nxho8F2EsHPAy2fqjhMYxax6kQ6HMohzE9+6JMzc=,iv:SgOgSDON9FT/KeOm5aFxmnV7QF/PspYWntRy/AdxA7A=,tag:PIX4Tk+lqjG71hhgmiQCkg==,type:comment]
    B2_KEY_ID: ENC[AES256_GCM,data:0b9/mJxzdGmZRcFMa99puDgp+576N00D5w==,iv:6X+3pWuPEWE3zRgkizTllyCWUQ075pDCb0bxUQu9VRY=,tag:wTlBqCtw81hlvcg1Sgviag==,type:str]
    B2_KEY: ENC[AES256_GCM,data:tZmXLWJi3W4igHnPQ20Gl0x9at95txWYOk1imvcvMw==,iv:oH0xdhp2gjVMO2glE6/4TnyJLk913ECNcltXH6w2NkY=,tag:zIwF8X7/S9MMhTZu4pGa4g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NzBnMm1PU0I3d013VFdM
            NjJuSFBtMUROMWxNRGdpWmQ4dm5aRXZlbVcwClF2WlFoZGF6ZEhoU1JUd2wrajh6
            NjlNdkpwUlhoTTg4TjBsKzM1QUpnbmMKLS0tIGQ0Y2ZIM2kwT3dmb2YzWkdMSzhB
            N05GSFIxeTArejhENVFWMDEza1dmTFUKRWB78d7a2z7F1+0c/3CYEKAEiHwwSzGo
            wKYEl3Pz0HpfTSrO9O+EzSHGt14005pNpHosbP7+1LMYA7q6ycg0yw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T21:10:05Z"
    mac: ENC[AES256_GCM,data:GJnuOnhOd9JQnRqq6xSXYgd2QtxKRta0ZBCBjfZsmyJXHYjTGFkRzl0OjtzYTleJ9OBMj3ij41VwFg7wMV1mBFNNcoDFA2xiLqnGElBLwJST1+PRdacopfz2pVngMJ96QyPT4ohNIz8tr6gIXY0ElDfCkC5eBs1WLALyWtpVw04=,iv:U5PoimGUM0djH8mKtHZrO5FQhvBkJD3d9oos9OTluwo=,tag:PR05CX4JWQCEVwJq7yuiNw==,type:str]
    version: 3.13.1
