# sops --encrypt --in-place oidc-client-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: kopiur-ui-oidc-client-secret
stringData:
    #ENC[AES256_GCM,data:7CxcfPe/TpWb+pQADjN/ej14vgYKX04+S8Mo2+3ZzsdHDomHXIeUHMeeMvTCa9c8bK88eZRkxnocJj83vARhrrE3wYFqrUHrcpG3Bsbt4kO0KMDleNlg,iv:D6fEojM8uktOXi+M/Q0ikMezDDVlSbJ/Zvparxsc2wU=,tag:59zQDSs96a958S+l17hJbg==,type:comment]
    #ENC[AES256_GCM,data:nqDOwyLr3km6iG/xHkMaJW19J9EzxXB7KIqtXaPCRyKjsbEl6w3pwSoyMAjgwWNiBWQpLCOleJcDZp7whTcgo5I=,iv:+O31n5bbsEFNwF9ljRy1OCZMrC1c5KkH/21LmxifwjI=,tag:27X/eLETY99riS06V+6y/g==,type:comment]
    #ENC[AES256_GCM,data:6V/1TDDen1Lqg7WirPj9KpDl0x9/jk1LdYpAIFSW8Zv4AUEk4JII1uoiVnRHiXYYBcQfsykJcTGLR2kJy+H/yyI=,iv:HKDlobJ3ZPxzQT3wEJY2qK2vsZX1T6iPHyz95P/h39s=,tag:Wk0ktii1c+e+9IxIj73PlA==,type:comment]
    #ENC[AES256_GCM,data:26sbB7nEZAMCGFpI6M8afZIIiBVpXIUTEQ5Sw2ObmowEDdWlglKMIq2JoCKB3ZrX1RMel4y53AJHaaT1Gh+etzWqK6CMOQ==,iv:KVBoG5H2rU6/aWyIDoT0c9hH4r7doMOjzlHISzWGDsE=,tag:9tNUp6n+1xLLY+BrcIMGVQ==,type:comment]
    #ENC[AES256_GCM,data:nz21pNzyowZTBvBg+EHOItcHCdnM/WI5RaMkriA=,iv:cCs1oIYXsTWE9WAZn8gbw/RjDVBFndGNRBRyIITmkjU=,tag:f+DzOYaGLZ40gXZ/EB2f5A==,type:comment]
    client-secret: ENC[AES256_GCM,data:/IwMCXGpxFEd6fvv/ZGsKoTuFubZRU167LiCZiYAsAfW4XPmQwU6G6zre6DU0cZHeCi/LDFYRAjsaaPmg4aML4iG+o64OIol2dxpKL7Y5sA=,iv:l0SEZJgoQ8sOmGqWuNmYwQdhoI9iM6SyLG3PZZgQj88=,tag:MdYKOG2oEzppZ061DhR3bA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYzEvaTNWVmZoZzFJTjRn
            WFZxbTNwcGN3clRMVVNpbGkrNnZkaUNsOVZZCmhPdDV0eTRvby9TQzFtUGw0Y2NI
            d1VPRTNlSjJmYkwyLzhNQVB0L1VrdWsKLS0tIGlmVHdKMnRadG1YQjM2WVowbVc3
            Q2xGQ0VSOXd3OVRROUtZZEJwZWNuYXcK5wI9Wn6xVjgUqD9Fug4cb9CXsE++l82e
            ufDY9LOmgjH+0DXgSK6zFO5FoaDIqFCBQIkzV7v/mdQvLAFvocMRdQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T17:32:09Z"
    mac: ENC[AES256_GCM,data:Lh8AkkxCD/i62qK3qgXftpRzuvm23qojSv5hFW+Vgme9EhMsol96ZsWSuI2n95fKdml+UyvYdGM3mYq/3CAu1BCMpjKc329i90A6Jw4pXXy6+1fwqoRlAlwn+8mna6cfyqDw4vaWV3rJZWXAVut+TQ4DWBwyLm9xZAn4WXayXII=,iv:9Pkl7EdKABGsIgPuh976bJf2PY8g/TxpzoGjAu1Ij+U=,tag:VLRM+FXZkGWPrYl+8WKDpw==,type:str]
    version: 3.13.1
