# sops --encrypt secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: kopiur-repository-secret
stringData:
    #ENC[AES256_GCM,data:8siJ/vhEc4U8I+VyQTAKhryex1kbwQuB7L6T6w58CWyEy7MzCCYj85uHjK7K4Ix09pmjIPOEnWPYAzl3uRXcSb+7K1Pufsw=,iv:EtO0fZ7dDUqVPlneljDSUdUWHew1WS6GXMvWHSiWBaU=,tag:jfBzvjHjcr0zivg8x/lF9g==,type:comment]
    #ENC[AES256_GCM,data:fIyVG0oeqaQG2kNavVi+W3raddQswr6BaiIpphLHlg9tQxIAQDDVmNEBpfROcjVqoNFXkm9dim3zMTYqr0p/lh37jnMQTQ==,iv:Jyc69vAPYmNROTVYqgFNtSXuDvpab87/mCyk2Degcy0=,tag:O1JZoKyNsNyr21iAZeN0FQ==,type:comment]
    #ENC[AES256_GCM,data:o0Rm9dXWpidTd61CmRqKENjJpRxNkRk=,iv:5hPen4acQJWFyObDzVQN8A3dH1Z75J9UjGhL+4e1sHw=,tag:A4r5RiU8sV1EYyNApSxMjw==,type:comment]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:p1tDDGfZxUwDKZTkHZD+wc1V2J2dUxhRKEwUlNaLOFeOQU/MUxlLzg==,iv:DSN8FBjwUddzDg/Y6c2rsPZYQic40p2QTpWm62NUih8=,tag:xTv/2zRbtAlwWMHIj9Peug==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkY3NZWFRlc1ZMaGxaZ2Vs
            UXJZWWdEQ3BoeWs0UjJHNlZqMnBzMFF0MGxVClpPV2tnQmVWR1hOTFhJaWJ1NVhp
            eXFNN09wM3I0VkFrUTNIUkt0K1ZISE0KLS0tIFE4Y1ZQZ1MzVTZiUm9kRFBOMEdE
            VnVjWnl3MkdTNU4vby9URlVLS0ZRY1EKwgAgB8gGuF0Ba0F3icqIblCKhAB5jLxs
            xOb7Ym6pq4IwzaHPtXCgTNbCkBTu0OprV4rSfiwWchivhZuNkuvIig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T21:41:11Z"
    mac: ENC[AES256_GCM,data:xF5qXQEnbocSOycZC9udGCSeuCOV25K3kJ0T3OYmB1xFmMp2O/RW+33OX4ymVxpoFVJJTP+dPgRQvdaRNcbmXB4kK1t6Z9ZAtGh2dVPLMMQJJ/R6ceFVzRr7J9qGVj6yFGEaEY2yYQPYroE5eS4OnkFkuzNOAwLl2QN110wEbww=,iv:DX02OmDHfrXi3FI7Wiuxm8mxNk9Wiz4a/AGHiu0O+/0=,tag:rRpCf1BqwdR4jpcy7fjgxw==,type:str]
    version: 3.13.1
