apiVersion: v1
kind: Secret
metadata:
    name: lidarr-secret
stringData:
    LIDARR__AUTH__APIKEY: ENC[AES256_GCM,data:XTKACsD2ZYtybKJ7jB/EwE5YsTo1DG1fFV0+26KIQcs=,iv:7RK11H+Ryow7//r2N91n4MW5Bhw75/k+2PpK09d3S6E=,tag:uTko2ei85B4SbNWhPNLJ+w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcjVLb0p0ckpIMS9XV1Vy
            dGNMZ093b1RWTUIwbnJBRW9xd3ltVWFoVURNCkZuc2k2ZHd4aERSalVxaFZvOUlD
            a3NSaHlQSGlqVnNiZk11RmJubDlFVTQKLS0tIHZaa2p6NWgza3RHK0phVzFDSDVF
            NTQ2dUR4V1hnY0x6a0g0K0Ura2h0OVkKCexb8Y+Y12PFCMVLuetsdJ9Pzag6tXYB
            w08aWH9cbDbVogIMwTEA9SgM98M2Zt98XOYck36QcI9WT5GR8CQwCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T19:50:39Z"
    mac: ENC[AES256_GCM,data:QDhGkon6hXcmCkvB1AkO9huJxhhDLpjtpFeACG25pN3wTHLD9Pp0svJW1iUF7r3Ytke78j4z7kQsu+RUavfSmgwk5vKf37Ldo1ZzUZGTmzLIWaBNloNplTi8KuQ1Obqz2SLRqpuhnNhQK0HTNb4qbHYlICxVU4lw1fnreGDDHXY=,iv:IIgQX9QAjJXKs2ZMQDiGwu4K1adGHPvPZVJeF3yx5N0=,tag:0PW8kM4/Wap6y/4VdR1pJg==,type:str]
    version: 3.13.1
