---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-gpu-operator
spec:
  interval: 1h
  timeout: 15m
  chartRef:
    kind: OCIRepository
    name: nvidia-gpu-operator
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    platform:
      openshift: false
    nfd:
      enabled: true
      nodefeaturerules: false
    driver:
      enabled: false
    toolkit:
      enabled: false
    cdi:
      enabled: true
    psa:
      enabled: false
    validator:
      env:
        - name: WITH_WORKLOAD
          value: "false"
