---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app changedetection
  namespace: &namespace home
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/authentik/protect
  dependsOn:
    - name: envoy-gateway-config
      namespace: network
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: ./kubernetes/apps/home/changedetection/app
  postBuild:
    substitute:
      APP: changedetection
      HTTPROUTE_NAME: changedetection
      HOSTNAME: changedetection.internal.oreillys.io
      AUTH_HOSTNAME: auth.internal.oreillys.io
      OIDC_CLIENT_ID: 6b3add39ea1dccde0d02f3f39a5346d677932cac
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false