apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secret
    namespace: cert-manager
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:QuFH+A0xB5AcfufYz3w5T0iIsID6UWeN1Q2dftArsuMYB2WlL9mzg3p5ploEmBcA5grGP0UZsqw=,iv:enlY3Y9u6Ikcq23vIk7zHRgP8pMXvxbPUn7vGf+8AEM=,tag:MPmaQ4F66H+eW3iSvP94Og==,type:str]
sops:
    age:
        - recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcTZrcEJySWFIQU9KczBT
            b1dqemM3R0F1VmlWRm9QZS9SMUR1RFkvRFdzCklHRERBVXJrazlHT3J3MTg0NHVT
            Nmxoanp6bGlzQ2JDSjBkWERXWHJhdGcKLS0tIG1Fc2VsQ0tnUVlmd2dpUzJwNTI2
            OU1qNkRHQ1J0V1BSNnRZbUhoaVIxUEUKqumcpsNIf5XezBsdrRXx/0LX68gAQnCv
            mb7Vtmj7Cw/Lv6ycq3v7gwlxEOfTve++fwUPYbAPcpm7YGDEHRNJpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-16T19:35:02Z"
    mac: ENC[AES256_GCM,data:86Iue7GHkFlgVJ3XHHWFGcChHY90XGwcs17Jr+Xw6QPXumsqHcvBCmMiqOWcUhFLLSds+JrJAjh4HAXmlzeHrsrM4yMfVjIPbtoPKilKlPrIS4BvRK7pfaw1ORjCnd9RzL58t6r0BFngEfpTGuNws3ejgD3VHIVWb+GI0btckJU=,iv:kArlHSwmDiIf2Hs82nC0nbCwbCiHRB9OY7c9Id06FBg=,tag:jUtRda1WfzTqxkfdAnb8Ow==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
