---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grocy
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: grocy
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      grocy:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: lscr.io/linuxserver/grocy
              tag: 4.7.1@sha256:d618bdb10eef88c691b8aa20d254d045c4f2091e705bb7736fe7fb5010c87f19
            env:
              PUID: 1000
              GUID: 1000
              TZ: UTC
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["ALL"]
                add: ["NET_BIND_SERVICE"]
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: &port 80
    route:
      app:
        hostnames:
          - grocy.internal.oreillys.io
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
    persistence:
      config:
        suffix: config
        storageClass: "ceph-block"
        accessMode: ReadWriteOnce
        size: "5Gi"
        globalMounts:
          - path: /config
      tmpfs:
        type: emptyDir
        advancedMounts:
          grocy:
            app:
              - path: /tmp
                subPath: tmp