# sops --encrypt secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: paperless-ngx-secret
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:EqL+VYOenWUBOGWsdLoplOHE5nwzoYuzMdhofwtsitPNH9FGQ55PnugusmW6dFZlMvmo+qOxWOX4Rgq8/Gu6FiqX89mjF5R8DjFFOaOeWLBEt+wvy9U2rW4R6/MoDE5hT1K6Nw==,iv:LFWVBUQr5cqtxI49XNPFP8Y2v62nsAEjDskHPDp490I=,tag:Fo+GJhdLmhfTMnN1gfSi5g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOTR3ZEFJaXY4eEp5SGY2
            NkFaUU1CNmVhdWY5b2lINXQ4d0hjckw0OERRCmo5VzUybVBSbEtKc3crUGNmSUdT
            Smg3SFI4V3FyTG4vclljdHEzeHNFNmcKLS0tIHViZUdXWmpJNjFLeGhDbStKdXlT
            YWhiTE9hNjlhQU5SZmdGcmdtWnU0RlUKFXTz1KmGju8NqOpDIGTGBv8FOuXixceq
            XbVhOylgqac+QUf84HAa2f/s+G2ra/+SAg7f4mZ/USYjGZQPNPBx2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T23:12:03Z"
    mac: ENC[AES256_GCM,data:l+U4z3P+npVi16LvzaDvMS+amWG+cOlERc+bbDoU4gy7gq1KWyh/ZKx6WxE25iJZ+2bnCaP6BbLZmRY5UBILVHBb24yDvUNK8mCuO3qZlqMe/U4CaJoQHjwYqFxIzjvsq61EcjCRtJvnIJzZG9zTzGwpBzlm281zIAw2BCbpjKM=,iv:HbqABg4sh2GxfrfOokFBO5IeM7DEtptAV5Fu/SGToC0=,tag:eSgjBTa+JaX5lgLUTXpdMQ==,type:str]
    version: 3.13.1
