apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:/b5kJnrTq/lwZPeTUJ0rSaR3m/twbtZbTM+0PzSBC4lA+h11s4s5Gg==,iv:kbu7Mk3Dn5bd4Mi/R4fO3ZjMnyGkCGK9UtxBP8tEQBM=,tag:3/nv195ml/CefBeqAxOSYQ==,type:str]
    SLACK_ALERTS_WEBHOOK: ENC[AES256_GCM,data:7oYa9iPgWdhG30+PEfU3r7Z15g2Q9wkICCq3yFdDSDkYAF7Vjc2KPoOJ/vLsjThPF0pl+jX2958=,iv:90OcYCcztDEmmqQEZJ8AQo+4UBRlXHI0jYE7ThIWw8I=,tag:KxTOpsFBgGaMOc0x29yUBQ==,type:str]
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:evRPRmHv8ItRz1FreusrHV0=,iv:7e7lPcgre1TAI7NI9COnx2EnAj02bCZCcNLzdtPq580=,tag:DDPD51gneNMFYuHX92pdQw==,type:str]
sops:
    age:
        - recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVk1WbU54U2x2amlLaVUz
            OWpvMzY1UitpR0IyNjBOaXJjMURQMlltZndvCkNjVStUZUtZdzd1bFppaldOMXdO
            NmRsNXFTZzJsUFM4ejFxeDk1bEViOUEKLS0tIHhWWnFUL1RuTE1VQk9Ea3ZyQUw1
            ekJUdGRwSUdlZEpPU1czVkRPWjJkbjAKUTr+FacB+LhjhQwdMIkYI5vgGDjCzWfD
            0foMRzZTi09NXEwcGNKUpX4CJqi4KYWXIvmrEgomtdKFfKcLdqDQyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-03T21:34:34Z"
    mac: ENC[AES256_GCM,data:XvuJMcSoV6xfCRmmCuV/6yeiGl3ZMgew1DVVAMLFyUlQSCsCExMbY6GRihtnh6Wt80+pf+nNZwFD9fgaby3ymTXTMhGsKdpRvByrUju8luGeRzaOWvysLL7SAvIubkPkk7uHvvBqGa/gws/k5mWYMnaCLVYzUVhBQsk+4q31iLM=,iv:d0onSdymjsXUoIAHod+g0rdCU6BXxvw3fkC5iFnBFAY=,tag:yix69aCVOJ+rB7RHchnZSA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
