apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secret
data:
    SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:E5GAayErC33vWOlg/rOwzCfWzf1afTVFCJIRnfavnm+DuBf0uNIWMGpr5Pg=,iv:KgxgBvf3cYeMJ3qIp1eC3Hu+tUrMddgNJx9z8Wh0TqU=,tag:/z+stRis4xEFsarED1ubPw==,type:str]
sops:
    age:
        - recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbmhzV1Bpd3BqNTNlY1BE
            K3gyR2J2YnlNb1NKOEN5THBOOVNablozNkJBCjcxMStHaVArb0JlYlhxRk9wZkJF
            bmNFQWVuZHJaSTV1V2RsWFNCVkxWdkEKLS0tIE5CdnVNQStwbERJU0tpUVozRGlV
            TzZPTlRtaEs0UW5BWisyRGFHM21aS2cKP5aOxoqRQZOIsmyuNejO1rSrtegSsX28
            ffw+gWTjYM/Ouu0+6mzzixFTWehbvniaPKt7fyu1ZKLT4GkAhzAH+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T21:17:44Z"
    mac: ENC[AES256_GCM,data:UyUtLZErnyQktnRaTPdnLD5vIhw5DqIIFB62sbyDAuhZ/u9LeBD2p24CZi6t3HVpbgKCrQ5X/zG+ivwdzlPsX3HV8oI/JP4VmgX36uNVVCGP1zX2PLxV8GoWYMeSzRecjHBnJxKo2VRfUPewF9Ehm7TihTjCYKWqo3obsI3c+0o=,iv:2p9gvoyCOajVLUsqCw+5ajdHXpwL7v4uIRXGnidVRMY=,tag:Nmj7AmGSdcdKxqDCIfHMeA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
