apiVersion: v1
kind: Secret
metadata:
    name: arr-notifications-creds
stringData:
    SLACK_WEBHOOK_URL: ENC[AES256_GCM,data:q7PCkwviRymcTiqcBhwwzGWIFadFCZwpdW/F5COZ2KhWbdT09o+JWLSsy3BcrnfDee7S4ZVdpC7uanhPkvY4oRjyzl4obpexp+q8rIeJc7mV,iv:ripTOmzqQDrsaV+6UfUJo4bmZpDWRqW/G1WxwAUDyJw=,tag:46VIHSfIH3f7PZNT9TzV0w==,type:str]
    JELLYFIN_API_KEY: ENC[AES256_GCM,data:pQFyVotM8DBkmsjwfc4XKJL1UyINn8FLLY7U4UMTpTs=,iv:zelQKrcO0gST6AlIWxRG+73+P3T6xaNw+MNfVSNVDbk=,tag:w5IkweSKPMzr+AHV1lay4g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBta1hYd21YQjBHZk9kK2Ni
            dzF3ajZiUkU0bGJPeEVnVVVSSXFKeFI4a3dRCkdxMkRNc0YwN04rWXByZXgvZjVO
            ajBOc1BMNlBJZDhsVk9OREo1MzhJdjAKLS0tIE9sQW9HS2NTRkpkRDAzZHI4UnRy
            aE9PeTY3WXUwUHhIWTVSdFBwNndUS00KLMPYa9WdLLLdWq3SsHvaDAum7dA/gMkW
            mSiOcnMMdrQa4RIT+/mqG1KpuXU+vny0EJmaz5unyDNHtMAaeErNaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T21:55:29Z"
    mac: ENC[AES256_GCM,data:WjLXwx6RDjxmy7ViTL2nwcXwFC7oxY5AXLgU+wCbye/vfnfiYNb6ft0ljzaJ1vHfZP32Q4iQiFnwlkN2tXrEjw4cT+E5h5Q0De9CTUEsTdml60L+fdOWoI/aEplM54o94e8KPGoSiCrqG7f852k80tLRD3iX639t/K/uMKyes/E=,iv:eTIXfFRF3ssO/va6mO6jAhpe0TCVw14QicBD1jrNGk4=,tag:GLpIZN5C/mw9LSf5Kan9OQ==,type:str]
    version: 3.13.1
