apiVersion: v1
kind: Secret
metadata:
    name: arr-notifications-creds
stringData:
    SLACK_WEBHOOK_URL: ENC[AES256_GCM,data:q7PCkwviRymcTiqcBhwwzGWIFadFCZwpdW/F5COZ2KhWbdT09o+JWLSsy3BcrnfDee7S4ZVdpC7uanhPkvY4oRjyzl4obpexp+q8rIeJc7mV,iv:ripTOmzqQDrsaV+6UfUJo4bmZpDWRqW/G1WxwAUDyJw=,tag:46VIHSfIH3f7PZNT9TzV0w==,type:str]
    JELLYFIN_API_KEY: ENC[AES256_GCM,data:SIedkZ/CjV6Uc+Jn9q1I75Xs3laVhSCxuEmgNYUi048=,iv:Pikq/I7s6kgfr7L+pzmIbPxaOzxADb4TwCfQaCy6WXM=,tag:FRvXNxDNMz8Pg4cOe7XNuw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBta1hYd21YQjBHZk9kK2Ni
            dzF3ajZiUkU0bGJPeEVnVVVSSXFKeFI4a3dRCkdxMkRNc0YwN04rWXByZXgvZjVO
            ajBOc1BMNlBJZDhsVk9OREo1MzhJdjAKLS0tIE9sQW9HS2NTRkpkRDAzZHI4UnRy
            aE9PeTY3WXUwUHhIWTVSdFBwNndUS00KLMPYa9WdLLLdWq3SsHvaDAum7dA/gMkW
            mSiOcnMMdrQa4RIT+/mqG1KpuXU+vny0EJmaz5unyDNHtMAaeErNaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T22:26:11Z"
    mac: ENC[AES256_GCM,data:mDLNw2iBJj5U737RwozvdxnniWUZYx5IB6CT9NtiXNBH6+vwduiGy8r0T/ce6oV1L7XUwWV1zsNwaaS5SZC5MXsi9wzmUoox/l5xW33VML8W97yaJd+1TD4wMmu89m49UxXwNJIqxfoVgXTicOFlUV6XQovAxq7ZRnO2Qg6+Ki4=,iv:2zWvsNShEpxXiY8VA5ZzdmN/vtYNy7KOwW+AgL0X1Js=,tag:eEIfdpNZjeExFIf/bQhoZg==,type:str]
    version: 3.13.1
