apiVersion: v1
kind: Secret
metadata:
    name: sabnzbd-config-seed
stringData:
    sabnzbd.ini: ENC[AES256_GCM,data:5n8o5zNalcbILEcKKtr+VfeAkTuTsoi4pxL0oCeR5qrvd7dpbBWwZbKsVrpSaNGE/975HA4zh4Q8TNFaHIvQjey+i5TP4cA04bJNK7INdZhEYdB4uG2KQTQig2yIh4yIF4QXvQGwk0ZNLrZsnGK24LONjhVUIJZa2fCFwF150YnnGQ36vGPSPK1rEsHNVPl2+dJ8xkFKmkwze5PiNCsFA7drDAXEanhA97D0dpAF4pl29ssmTeSAsTTU8B3siRdY0P3AFGkhwTvvR6ns036wqFB4k9dhbpJTls1yB5b6on/cKyCdLQKo9BLSSEzpUzYFhW8iVqodcALyT4BcMFJ+uhu8b9Ks9omBMNL0bSMm6EiShFgehHmF3WB2JNiewJ9HH0JZfSg3l5d+o1lOpI2REqdTYKeiS/96bo/wAMZd6pBI2kknbBlKKs28Na4oWY7jOjAb2yDo/TwtKuNb0/9BlYcBASHXk3XMMGKCJQVh7wUsrmdSzV//682hRXVFxknOWt/CWNWMnJn4NmaLor5hw8XuLToOqQGcPo2owjUM/k9+p2Z2Z4BGRkkgydA+9YvSxCkqup3gf0TV6qb/dxIMw4vwvIegwAoBTXckQtDQd5WtDy/0BO1Esus7l2SZXCE2Eq3UElnArQOqyxHmvl4PJlUWI7c5HMNqkACvZdk/CoH4p8HTaHFNKQ==,iv:lqE6blLkGS9jxQuYIAhsg0Dqr/uE7R2A7wBpfHWW4j8=,tag:c7vGVjDeubclpWrcs5uIJQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsYkRoaklZVXZ3Zk53WXJy
            Z2xsajV0Kzc1TlBDd2cwRitYWFhlWUV6aWtFClVtUVJ2ODlsVTlLT2lWRjN2RzQ0
            NE1Nb2ZJK1JUczVIcnZlcmpUT3RhcVUKLS0tIEg5Zy8zRkhyU0NSVkRISGNXRE95
            TmZnMVZGbEVMR2V6MWtFZTZUWUtkZFUK0QoeWIZkBXLWmVbVWVbDwwxUklIJsuu1
            Oo19QqflOOfrXgoLR2SurzUmUvjWSLRp8jFmTlpNBxgeUoeICJ1BGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T20:31:00Z"
    mac: ENC[AES256_GCM,data:mT6l7x88VJf/3E8RBCeuwfQfN/MKJoxUabS48JZQ4S78wGMeOJF9iImweGmNnVpFg4ZtnzBZK8Z1AEtGgYGmxyvqz5pCc7bXaL/aJhSLrSykAErtNqcu/27l4ZqSHcqNpPmpQGbmlQdbVuPsFrzjsZMVd1vdBu1HeEYEmT47Pk4=,iv:z3DzacHdVahGYwu8u7cqzGXnwt0r34TgIXVrz1bv9/g=,tag:Kv/wJ7DtgQJ74MfZjcpiUA==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: sabnzbd-creds
stringData:
    SABNZBD__API_KEY: ENC[AES256_GCM,data:I8FBgFWqane0cwYQV7V0Mn5VF2K+7GeOVrcRNlo/iqo=,iv:F+u83pIPE+HyrUR124rAwDPbdauUsd0kA0yLKYaFNNE=,tag:BiXeHPIRNzbG+D518W7mPQ==,type:str]
    SABNZBD__NZB_KEY: ENC[AES256_GCM,data:J2PUjp4w4F9ExRPxn5l/ZfwoGQH7jpwz1/XE+lYokKw=,iv:voz7svd2G8YgLjYrYXPIM1jViCOeDVrPQWbVM5oW0pw=,tag:QI647rfLNQnuqCIatXFO0A==,type:str]
    SABNZBD_USERNAME: ENC[AES256_GCM,data:VtUhMw==,iv:EdncssI3YDWSzjoD1aBVyWG3W/zQGTxSnGxkIJd9hAU=,tag:NPtcNlW3IzYL0FVeiMUwEA==,type:str]
    SABNZBD_PASSWORD: ENC[AES256_GCM,data:ovEUk0gdoNiQjVShIfuoAhI=,iv:1JwdoN45f0o+MGUE4xVfhr7/TpeEqhToLXgxY4c0v38=,tag:g8Aw1h4NPBUdKJdG6nWmbQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsYkRoaklZVXZ3Zk53WXJy
            Z2xsajV0Kzc1TlBDd2cwRitYWFhlWUV6aWtFClVtUVJ2ODlsVTlLT2lWRjN2RzQ0
            NE1Nb2ZJK1JUczVIcnZlcmpUT3RhcVUKLS0tIEg5Zy8zRkhyU0NSVkRISGNXRE95
            TmZnMVZGbEVMR2V6MWtFZTZUWUtkZFUK0QoeWIZkBXLWmVbVWVbDwwxUklIJsuu1
            Oo19QqflOOfrXgoLR2SurzUmUvjWSLRp8jFmTlpNBxgeUoeICJ1BGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T20:31:00Z"
    mac: ENC[AES256_GCM,data:mT6l7x88VJf/3E8RBCeuwfQfN/MKJoxUabS48JZQ4S78wGMeOJF9iImweGmNnVpFg4ZtnzBZK8Z1AEtGgYGmxyvqz5pCc7bXaL/aJhSLrSykAErtNqcu/27l4ZqSHcqNpPmpQGbmlQdbVuPsFrzjsZMVd1vdBu1HeEYEmT47Pk4=,iv:z3DzacHdVahGYwu8u7cqzGXnwt0r34TgIXVrz1bv9/g=,tag:Kv/wJ7DtgQJ74MfZjcpiUA==,type:str]
    version: 3.13.1
