apiVersion: v1
kind: Secret
metadata:
    name: podfetch-secret
stringData:
    USERNAME: ENC[AES256_GCM,data:vhm+2Q==,iv:P7HFMnom2qpq1NYPSL6WXGOuzAWp4kcZGHq/DeO8fTo=,tag:fB2uGnYaYJFgAv1s5A3zEg==,type:str]
    PASSWORD: ENC[AES256_GCM,data:JFCfcGIzQgjEz4KLxI8s9zr/,iv:Fb74zADGSdFBfVNvtsLg8TVwt0oe66wEROAKn4X/pJo=,tag:oXGhr3CIUzZuOIoz+VGXDw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBualVyYS9jeU5KWmFKZTJh
            cWVjUEJBV2tBQ2Z2dUpKT1JzQVZsZGJ6U0JFClc3SjZwMEw5WlNFa3lxSDhjaFhh
            NWQxWFBHb1g4YUlRSFhTaEhKNW1VeUEKLS0tIFA1dTFtUFgxYi9CWWw1VGRYb0lB
            WURMYktFd0M4YlQycUlWTWRWNC9ybUkKYwsQ5JU9VzNXxbxWpRJh/SK3CXFPOn13
            NrCZieiniM/c1GnEWGCzmKJHLCcHFITbVzNnYlq/qzXr2ZFmCwdwKA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T23:17:04Z"
    mac: ENC[AES256_GCM,data:Rse9BRa+tsj56KsDJwYyV+l4etvvDdPQgKvXBCw59M5kKWVJVwbM5BxJsA0zYuHyw/2pE5xuGv6Ytbi232x9PqM1/DyHRjg3jR+KaoGPE512pY0/zvFg2d3OiZRGlKLgZQf2Od5/IhKxa94JMzOtu0/azIDKcHIuEbGBgaWtTeM=,iv:jnvfei/rhoy5gHrHjg61cv6pVn/Z2HH5I/tTMUHdu3Q=,tag:EPLyNrt62AGNBa5PNqOGSw==,type:str]
    version: 3.13.1
