apiVersion: v1
kind: Secret
metadata:
    name: bazarr-config-seed
stringData:
    config.yaml: ENC[AES256_GCM,data:MLFtuzFbV4H/VsLhd7G20OLK9zTK6QBMzIu7/RjXNCt0O8/+BGq9M8YAUEleDmzEkH2vQoXg2teATJZZIZvuesFSue9ev/vGQDmi5473Jg0hOObfFZTTvkWqDw5VOfq4hnlo3ueUoMVVfF8aS4T2iUEIOYbQiVgPuGPcEblTCu/1z/GpPlsubSYHSw3sF5lxzWCdIviB50cDYqXoWXIHyOlL3w/rNYnthtzsUi2HrmDEqOAsEEhkNCQdN0bD8vo/pbgpFtdW//l/CUsxn7XiMDjtxevTwH4qUYh7X94/6dHgJSwAGJiNsYsckB12cy7jrvkZc9n4as92J5tpbm34ehwxFQ/PniTuY+FlMoIK2mRAeocG2mJ2ZUoQZV4CRSfOINKqA0I1sknZp/8UiA5kgsK3M97D9p6dFr3lyet9I/AGLmrqZbAXSI4G0KITTk2XVlt5QhW5bg==,iv:3lAX5Ucdck6bvBcp500L4gKe1fFxd+YcYF8bX2qTjCo=,tag:FKlI3DhSwnknZtO7Iqblhw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYaG5zd3h4VEllM2h3RFVv
            akt6N28rdlZCUUhMOGdyMXZGOGxvaWxrc0U0ClZZNHdUMCsxQ1BWOGEwUVBrQ1Ja
            WEg1cGFad0hLeWlRMm0ydTltR3hoQ2sKLS0tIEJ1N1YwTWtzME5yUE1iMGRDWWc4
            KzFrRUc0cXZseFllQmtIWnpoUDZHd2sKkv1V34gHQRS8rrJro/ItazSEdwMBuyfn
            ZNFHo4hdRbLyEzsB1+KoqhgZQyelWj32c3guIp66vx+yy2JX0uytqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T19:49:55Z"
    mac: ENC[AES256_GCM,data:DMIIgSBJr/B/AtDaAJhDCqJkldSph7gmf+g51dxXtQBIZm87t3oOKvwF5QpFbNKOqiiQsN+Oiw6wONV7Km7tJj3oBg43rcqAi2bUU/dPC07IHKZc0X3rwcNBkDk+IEB1H/nSShLMVsuqklUc+S/KdGa5MtYMXQe4WlinTaGkde4=,iv:Di5p6qYKHdfYyAAR2zL3oeTSz5ooqP+jD4CtrsZmFi8=,tag:k2eSp1h7o/lCc3HBFBppEQ==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: bazarr-creds
stringData:
    BAZARR_API_KEY: ENC[AES256_GCM,data:2SLbVIOhxVPCkBj1uV7tIQddL20btmhB+RsV+E1xq9A=,iv:qBZHZQlKG293dz9piVIBlPn6vJVc/BfeR8p0kH2Ic8E=,tag:9qnGrx2j6ELexSLMU+9brA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYaG5zd3h4VEllM2h3RFVv
            akt6N28rdlZCUUhMOGdyMXZGOGxvaWxrc0U0ClZZNHdUMCsxQ1BWOGEwUVBrQ1Ja
            WEg1cGFad0hLeWlRMm0ydTltR3hoQ2sKLS0tIEJ1N1YwTWtzME5yUE1iMGRDWWc4
            KzFrRUc0cXZseFllQmtIWnpoUDZHd2sKkv1V34gHQRS8rrJro/ItazSEdwMBuyfn
            ZNFHo4hdRbLyEzsB1+KoqhgZQyelWj32c3guIp66vx+yy2JX0uytqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T19:49:55Z"
    mac: ENC[AES256_GCM,data:DMIIgSBJr/B/AtDaAJhDCqJkldSph7gmf+g51dxXtQBIZm87t3oOKvwF5QpFbNKOqiiQsN+Oiw6wONV7Km7tJj3oBg43rcqAi2bUU/dPC07IHKZc0X3rwcNBkDk+IEB1H/nSShLMVsuqklUc+S/KdGa5MtYMXQe4WlinTaGkde4=,iv:Di5p6qYKHdfYyAAR2zL3oeTSz5ooqP+jD4CtrsZmFi8=,tag:k2eSp1h7o/lCc3HBFBppEQ==,type:str]
    version: 3.13.1
