---
apiVersion: v1
kind: Secret
metadata:
  name: bazarr-config-seed
stringData:
  config.yaml: |
    auth:
      apikey: 1kowq3t3f53sf8bxbadqkfihuw5l3ro4
      type: form
      username: admin
      password: 41fb0c03fd024029eee87a043bf0a1a8
    general:
      use_sonarr: true
      use_radarr: true
    sonarr:
      ip: sonarr.download.svc.cluster.local
      port: 8989
      base_url: /
      ssl: false
      apikey: __SONARR_API_KEY__
    radarr:
      ip: radarr.download.svc.cluster.local
      port: 7878
      base_url: /
      ssl: false
      apikey: __RADARR_API_KEY__
---
apiVersion: v1
kind: Secret
metadata:
  name: bazarr-creds
stringData:
  BAZARR_USERNAME: admin
  BAZARR_PASSWORD: "xN_3yxTV-mr1c_KzecQqTi5T"
  BAZARR_API_KEY: 1kowq3t3f53sf8bxbadqkfihuw5l3ro4
