apiVersion: v1
kind: Secret
metadata:
    name: sops-age
data:
    age.agekey: ENC[AES256_GCM,data:92YdnUa+EBNKQINSY0Pe0VVB6uIT4G97PZM7kMkDp62RC8jGNpSePwSzh8CUCqvJwLOszzW3O18CKtoAXw8rAbd+E+iFRIL8ZyEpPLFtpC3VZj22gLmSaZWvT4snyP7HxVuNEL41rUMxEiIuMnm1MAvOzjp4GIbnnigaqvDexrhtcbeWckcaaHA6gB4gINJY+wIPHschjt0+cnKCxU0+ag2P5UDHVsBXsQcDtvoRQMTOGm+2qF/OtdtIvoViTNoALIPV5nf9d06e5FdqQ1byMzTFnsu/ds6aSUWPvKE4NTWUr2IqhuWkDKskxdNs/7cbmV/SS6xy/NB7HjdB,iv:bafKEOaYDwOjXdWUq03Ku9MwBolLeDImTg+v7kD4pOM=,tag:7pkLkxP8zTICI4gpaveQKQ==,type:str]
sops:
    age:
        - recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVHlZaWlxU2ZhQTErWjVp
            Qld1aVhNWkhIUUgyQlgrYnhHbXNESm1BT1YwCmdrcmxBS090SnQ4MGFERm5wbE5F
            QlZYOWNobytxVlcxYXc2TVJ6NENwNWMKLS0tIElJWURJRFJNVnZqRnFuNEdTZkRX
            M1JJenZaQlBjNjIyOWJLdGFrSk5zYncKW3Ky7kIXiwUm0khMXc8CclJbOBYFZhcz
            L7v19wHpyGoQfW+75j5CGUX4UqvtVh6PVtcf0QVFgSpIMfF9w0Isng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-16T17:33:12Z"
    mac: ENC[AES256_GCM,data:Wi3nfZRSeX4PMLYhBE3+H+qG065UTFr9W7mW/mJ1z08H/PTTLdNp6bmfCiKpaxuAm11MKywgqAxoZiltsksHO51LIzzcRLbMSts3sw4AoBEky0aEGQ7nFhFFum8Hsj9UIwEr84q55LqjyM8UmIqXQbPdLoOEzgrfE5mA2ZNJQhM=,iv:dReGNgLokZuSlXvbFtjksBMcOunzYjfLnaCmeUEdWVc=,tag:ZkmX1ms0dnln6+aFYPzubw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
