apiVersion: v1
kind: Secret
metadata:
    name: mylar3-config-seed
stringData:
    config.ini: ENC[AES256_GCM,data:jJcff2R1q0LgBmv/NdsmeVjgaaiKjFlthqSfr+zgFRhDG9HP6P3668HFPwWKCDbccbNvTTRX72lGylHH0CDscVBiE88Moyt7ynxbPIABMRyfZT5f7gdMK9ZfQjeKOixMWCIQzijbUo4NnH5+CCngC6CkWM7C/xtFM52Vw6HIQNCz382SViAUtCXSZW4mNqwkCnKaSXbHr9uJCQNCtssQ8Mb7a3Qc/QG/eajRRprEBmRlDpBZ2uf0hb6i1gbdKrQipzB/d5KRWYzHF8LTmppMI4veYflXx6YTdnrY+qWvcDzCoupQnGf6KrJLcWtiFnL6glOm1TkaJezmmRkBRa8CmRkoZpsWCDzpUQytTpRbzMusIUVWuSRDZmplUMNgbfCT56nxRhU3C8c3j/Lgq61VomWUsxc49lEPE0rCt7s9EPTkPh4hkWHVU+WtNzUQrP5xobC8gf6fg6ze1J6GvF5qY6Rcfkss7foQqjmvIfAkowLeQ+kYCki1D2OUQII0RbqGMQsYKmgvpvl4vNfkSqSxZqWAqk/2bwiXJ4FFFl8k2wGrs9cq4vxGvjsv46jN7E59VYOtcu50m9wy0Q4mGQbiNA5lQDYM6e+nhCGX/eOrGHRuDn2zidbfZb0UN1l24j879f21+zfzxRWczDDD0ZIS35pBAdvX6ASPblbF0gQGtkNyUXBXGSLEVIZlLoVPsz9Ukzg0QN5WoRvfgUq3JXVX6lywKFQSBQ84BOfATjxMEjY1LrQ9K+RKDZv/sK3PG9GAFwgNba2lUagtrg3+WvjmAFlEDKPossvMZHRMtSDkOcBcqK5X7fdLMPsVQ4dpQJvEh5WEH86onIH93A67KAymWuVGBDPDu2sdzysMsbJisQ57Go0r1IndNi2kQL6gnfcwuz5jtEUpDdqjXsQhl+xJO3gf6mffGGQ2pkrcZK9JAHGVBgwfKl4z68Xe575aZmaIWN59RrS2tIePVj/Vhp18rvQFSLWdlRUneojIP3AYWS9MWyNDGSKedadxk5IHq+t+ZUB5NT5hfWM2q8R6,iv:gJZ4dIxbyG/+O7qKSJK3ultDKSwex/vIWXE1uvH6VlY=,tag:IiNJC617iYYBJ5t2uWcXDA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINitteUREK1ExaVRtZnpk
            aHFSZ0JaRGtpci9vNE1hTENWaGtZS29vdEhjCngzRXM2Vkl0K3ZnbzRFUGxlVmlz
            L3lLWmZhZ0hxeDJlVkFsbmhKQVYvRWMKLS0tIEVRNTd4ODRib2RhL1JBZ0R3TFRt
            TE4vNndDZnhHYzFteHQrZ3F5cnF2THMKw+Aqa7VncwCQCK+x4WY65SB+TEaUUIVG
            X8u8PSD3Y35v5Nff8sPY6esrwJHtpw9SnaFYUSVqyGYy5u40oQAwpw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-03T21:34:07Z"
    mac: ENC[AES256_GCM,data:KUrQTfazHSSnGKCWygydmIuKwtvdhRaPJg5PT7uJ2QelKtSf2eIWcHFh+f7yV4f/k1gb3WxP73g34p3KaTLNEYZbR+hv3jatHDG2KuROo8Gjx6nP5rhWL/P/h1AbR1QR/pxNmOGm58IoiIh4+nfP78nFR1W9dhxLzFyrfA4AX7s=,iv:2Tq81ouukmYYTP0cDWALDdA33xRYfx55XHsxzP242WI=,tag:NXaSalnshF3vlU0EYp47NA==,type:str]
    version: 3.13.1
