apiVersion: v1
kind: Secret
metadata:
    name: navidrome-secret
stringData:
    ND_LASTFM_APIKEY: ENC[AES256_GCM,data:HvWWDgmU76ZNWx7Ignx9Qcpx8/HtHilNk9Cs/gFY0wE=,iv:iyXBFcgmcChK0vtWfcYchqby9xbLQChqhrEW+ORtnGg=,tag:nupYGvI9Q/DN1N1mcldP3Q==,type:str]
    ND_LASTFM_SECRET: ENC[AES256_GCM,data:MTjlLAwNnT2q3UAj8rL/T5HCz3P7xFhRqalZF3dTGuo=,iv:/5j9oBN+ie1XYLZ0t7ITmb0BTlLPfl/Kr0/tkGWzFPs=,tag:FaGrbISbHBnZnZZEaiYp+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNmFZMWQralYyZDAwNjV2
            aUQ5QS9GaGtjTDFtZU9naFcrY0pGWnBGZzB3CitZVWYwckFuYXl3bEtSMEErNEk4
            d0Y3SGpvblR6Tm5RVHpUbEJyWWxHdWMKLS0tIHRNVW9tYUdrcGZLWmxKdmtIRTY2
            VXlhMkN4bXU3dk1ycHk2L0QyeVJORVUKZFYl9vnuUGtRfs7omFFo5jx4QTWUjLhY
            nFr7EAo15oK7MitXrv0De4Hz/76vlQ22vPpCPS1IPfczzDT3qMVeLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-01T18:58:08Z"
    mac: ENC[AES256_GCM,data:hZOhL+06SSREFM+zcFYvM5ESHG3hx04NEn5hAlifSE1mjDmgR/4awe6dwZxSOsMGAZ1hAGN3DLrDK33wOwJ8MgGM9jwkcgVbJITAA0p/ROylNJ9GJDs+alKLzM5ZxuLtVIaXi+vX3GYTZ5jJyR7344pDqr7jwed96GLwVtzfuFg=,iv:Oh9AoJP806c1XLsQFX5N1KJXkdC6ttSDwnAVFGFswnw=,tag:O4Mdau2I51CzyxX8NV6Lyw==,type:str]
    version: 3.13.1
