apiVersion: v1
kind: Secret
metadata:
    name: bookorbit-postgres-creds
stringData:
    username: ENC[AES256_GCM,data:ju/rr6aP33iW,iv:2VdrM8RK4TDxGRlvVlNc2c0ANQ63ouYd7Vcv9/ftOcY=,tag:ihNdR3OZLDtWBizMksFU+A==,type:str]
    password: ENC[AES256_GCM,data:xVPlR918es/pOYfn054T5gb29jWQXcFpewe8sUyb9G8CJyXve34o/TUtMeUjjz7m,iv:N3bEmwvZTiC7RMoG2AlUWzZST836xMw3/hULnHaM9Kw=,tag:bQhHk0LiGqU+Uv/Ho7p16A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMzNYeThiWWd6MXhLUGZ0
            WGF5SmZSOWV1amtJakpFdWhVcEpKN04yd0VZCmp0TTlQbmdHY292eTZWbFpZUzhF
            bnNqdU9PbDhPOWlVOFI4UDJzcG9lRkkKLS0tIGlyaUNJK3REQTdzejkxVFAwanRM
            Q1N1a1EvK0EzOE0zWUw4TkhOVmRXdXMKgu0OCwOKoS9SZ5GGt5RnULm/j5RculKa
            a39s5+SRVOWJlhNgaouFIqeFG35AsjEMCiBst2pXGNMnzEZf3EijHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T07:45:06Z"
    mac: ENC[AES256_GCM,data:cnKnSJwLm9V0r6lkjWRBPsJcFZdiGqI2ZKowWuPz4lknudGNnBlu+RzXTVJ1J1VADckahs039qgOWd2sp7FC6QzEQv6JZUuK9maE57t4wXrvzM7VjPiAV0YSMtNLeCpzjKGf9X8i8XYdf4GogGoPV6r50MkAGWO8n7YbM3Qq+9Y=,iv:rEqS1JKjSx43/D0Pz6je7x6h/+7uXKhpcLyAf9M9k4U=,tag:MOpeip2h0iamKt0gp3+mqw==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: bookorbit-secret
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:gWAPjZQDHRXziCS2h/f44TRwyM9BbT1sjzGjZu0268YwHdwQdI2YQ62fkFs=,iv:LX3o9vBFuphL8XmRELW5AQjKn9R4CwpVMVbijOaPd50=,tag:NsGMyM/oYdxRoc+EYnQe2w==,type:str]
    #ENC[AES256_GCM,data:meZ5a6AXfs4RejQB/Oq+C5Z96Xr9AnjL5+pBDHDCefybpfqFoo7vBMTe5QTaI7ln92qjvn29Hj3xKKgc+o8Q,iv:IPCqz6Biy6Qz599zdZ92D/9VwwVMMQwgVRRS3ZyE6iM=,tag:X8S1RWXnUXz0i1QjjHy+OQ==,type:comment]
    #ENC[AES256_GCM,data:4RpJubwFgQcN8xtPRp2Nggd+9PtqatZK1zOLPXRhddx2bmnvNPozrl2t1pDRbtE3yFZwNrG2f8uWHTUuBaQ2dw==,iv:HUHLtJcIZLfTaSmEEeqToVntx/O34ksbAbS1yL2GkSg=,tag:QyZftT7m+Iv8Y38CFTedJA==,type:comment]
    #ENC[AES256_GCM,data:kgu4svSN3V4yD7MJSoi53kN+AzJ6jd8=,iv:dCpcISg6zLmmp4rY9Uotcu3C7yZPqscbIe6j/FTegC0=,tag:FkAym+IRQ+xZWNfIwvrMDA==,type:comment]
    SETUP_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:6gjMsSEiFnlNYbE/deCOvHLcERdQR9fqzsjdcSk+1tVkPUIUxxW1/DX7hHk7RtNE,iv:T3GDZc6M7I0TvBSsoS5KPe1AvL88jAyacjVrqI28nYk=,tag:kicNG3HilOg9RGdKW0GQEQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMzNYeThiWWd6MXhLUGZ0
            WGF5SmZSOWV1amtJakpFdWhVcEpKN04yd0VZCmp0TTlQbmdHY292eTZWbFpZUzhF
            bnNqdU9PbDhPOWlVOFI4UDJzcG9lRkkKLS0tIGlyaUNJK3REQTdzejkxVFAwanRM
            Q1N1a1EvK0EzOE0zWUw4TkhOVmRXdXMKgu0OCwOKoS9SZ5GGt5RnULm/j5RculKa
            a39s5+SRVOWJlhNgaouFIqeFG35AsjEMCiBst2pXGNMnzEZf3EijHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T07:45:06Z"
    mac: ENC[AES256_GCM,data:cnKnSJwLm9V0r6lkjWRBPsJcFZdiGqI2ZKowWuPz4lknudGNnBlu+RzXTVJ1J1VADckahs039qgOWd2sp7FC6QzEQv6JZUuK9maE57t4wXrvzM7VjPiAV0YSMtNLeCpzjKGf9X8i8XYdf4GogGoPV6r50MkAGWO8n7YbM3Qq+9Y=,iv:rEqS1JKjSx43/D0Pz6je7x6h/+7uXKhpcLyAf9M9k4U=,tag:MOpeip2h0iamKt0gp3+mqw==,type:str]
    version: 3.13.1
