# sops --encrypt --in-place b2-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: rgw-nas-sync-b2-credentials
stringData:
    #ENC[AES256_GCM,data:ZRmZqQAXul6fozdOrd57XhCtuzGz+zV+C0xQPf8RRfXy+peTMRt+Fp9IzqwG8nryWsBYLIkTwuAoHerydw92IiLqbECXgwQoobYJ3HFuV2dKCNJUzarADIta,iv:yym9LfomwLSxK7voEivrZNr7Re2JT5w2E6l0jjNMdQI=,tag:/YNy7Mlpxfd8oLw05GevFQ==,type:comment]
    #ENC[AES256_GCM,data:SHxyXdBKRcdFuCJcbicsE/XjTa/EJhZZJPGTTG1GpskLx0zlIy6Ps4d8zNwebBp2XfcrXtRfdx9KvdQAD34QMThrb5M=,iv:DLvbWGhQ7pTYQ1PbRxPIMqhzNGnQ83jq/nQEHehXOHo=,tag:HWhXpYtbbqLXyJGseIz9xA==,type:comment]
    #ENC[AES256_GCM,data:HcBIYyOFV5cznxT7BWY1dfvVF40WV+qnDHYac2URY4TiEv/n54c81CYkFgLSGMp6YHgSdL8ic919bsBgKmkh29yiAnI=,iv:JQENG+QXnatpMNyYcAD/NMR8B78HrEHxVUf+g04xOjE=,tag:bree+gGnXQF+MgIvgTwSKw==,type:comment]
    #ENC[AES256_GCM,data:NTZJaDp1+J0U3Qrpkz+JsKVgmGxyupelxcQp3LB1TJzeIZmT7gVSNEcnZoGWX/iF/+fSejK5PQq4iCj5oauaDn8XbguPyA==,iv:1lITaTCXqPvlr9u/5jlGXKorMdhikD9wtlEYSl8EO0Q=,tag:oSJMFRKHwU2yn+3QDMgtGw==,type:comment]
    #ENC[AES256_GCM,data:aSlODwSkc+GqwfBoGOiE2KbJExnRsF1+/FrDoMraRNzJ7Ub8+PTv0YdKJDXRDgYudw939nBX7VOfyuYWtUzUh5Mur0PIttDdZb/N,iv:XauulVuZ4ncSIhV2VSdtqEzlEOqj938DqURHamJN4yc=,tag:5SzwtBSvy/6bthEAgFluWA==,type:comment]
    B2_KEY_ID: ENC[AES256_GCM,data:JxnKXFYjL73Dy1kfE+s0Quh9R4th86vT1Q==,iv:B7Et+KkqzZE6kvZ1o5xzyYRC7swZyFzxJBhb6vjiGh4=,tag:tkOwxEiOWqLHRwPrsiniSg==,type:str]
    B2_KEY: ENC[AES256_GCM,data:VUg4rVb7ATGiN/x+rbTnIIycIXXba0/BNK6DZaV3Kw==,iv:ZNAK+NKMSNHQFETUz1U0uoZKkvT7ccb+g9eD0unTL7c=,tag:LDrRUgem7+vPZHQae4OL3g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5QjNIbHFyYVdVMnZjc2Fu
            dFJGa3g5T3UyR0JEa25BNkdwbmU4ak8vY0NZCjV4dDZQWmVyOGxDdnFCazZXVmdo
            NkU3WG85UGtHU0xpREc0V21ROGtHN1UKLS0tIDlFaHg1a2gwUnFQeVpDUXdIL2F0
            Rk5GZEJwUmJlc1Rva1FXcUJwTUE4NUUKrIeHAkZjQZ2WBbS6kQJn+egkV9uo5ccY
            p4d+p11rtqdVzNl+OuXcZdHQIzBn0GEjDCfmXPXPJ28x090zAlRdeA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T21:10:44Z"
    mac: ENC[AES256_GCM,data:ZxWHuLCx1uQ8sw5xPKWLcnyqruRyEoMnzE+Sf7/3w/yJdwUoIdqn+SB/7zcjN9tE1YG5njfvTFp+ehtYJ9aACd3GLPDNnJ1/oqAarkayu8wHHGfeuqyZ43XQMczbLpCnAQkqasCOC8DXqCnPNioqcedyhu9hWyRMgk2pnk2/nFk=,iv:R5iwkMTUsRLP5ImY8IAYTP2L/cTQrCkdpcsquxUuh2w=,tag:60IcEG2HYtTuczh3AddpuA==,type:str]
    version: 3.13.1
