# sops --encrypt --in-place b2-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: rgw-nas-sync-b2-credentials
stringData:
    #ENC[AES256_GCM,data:Q3SsIDlaZ3+bPqxeMZnk9Pe9CnkpZwIpcZs8DSyXlmr/9WvM11zYBKRD1vwzGrVoNxRGhw5GULGa6CTpIJJGAZSL,iv:NAQgJX/SFkGX0JpUo/VWNCA+fTvNbBwlSP+1xxO7Xic=,tag:+4EKHUjoAVwfPuaOHyrBYA==,type:comment]
    #ENC[AES256_GCM,data:6GHrcLIpMY5Z6vXebGVKTS2HmPCiE2dGCVx7CZbr4Tr/zPl/IEIf/FDvdb6W0kLvcOMSt0XuaHE5tA==,iv:TjCAygqyAxsc7yBP1HvmBipz9spxRMfpSIGRUqbfVnU=,tag:hcv71HuN9LeqCjF9ANCeyQ==,type:comment]
    #ENC[AES256_GCM,data:GtWGweIP1FJ69B526Vf3+vxdshxnP2/YfppIO3WRLv8COj4HtwooR7HMtl1ym9kF4t7FznqDvJFbVsJttsncaHJ3pEoh5/0z04Rj2FEFD1bl6z04nqo=,iv:ofayli+PuGFI6eR9Cw0OHikqdWK2QBo8F4o196uKbVE=,tag:g9qgAZcsQSibzNaF/Fm2pg==,type:comment]
    #ENC[AES256_GCM,data:Xp4zwNfbEFpHDtNdm5B6KRdE8KRF0yMG3LRv9ccowMkgPG9xSGYPFTxAfDWBDmYTtCvgGrnMvPem7Zq4GqcCkA==,iv:TIRql4ZNwnclEkje8fxl/ZnMvBfZwLSiZeQ/EV5JNfU=,tag:mji0yZT/16+Ur0M9uU9U1A==,type:comment]
    #ENC[AES256_GCM,data:jhh8vfLQnYJXgl/e4PR4YpZ44a13aR6OrMUVh6DlzSJCG7SV54ksgWHYrdLbDO5SKrS5yOtXni55vDocZNpRNg==,iv:QB5tC8aPGft3mmcoLSVowQCyTd5UkpuJUeKp6x4F8HY=,tag:XBENwY33bZKrxdt9Jyew3A==,type:comment]
    #ENC[AES256_GCM,data:VzSTaegotFRQEqyhipGT+VG+5bqc8KUdhRbVaUKYxbGtPIpmmSQZ/m4ruoprkHzcjflZ0Vjk/Z4FHixpfE6BBpNaVsw=,iv:L+RZVJ3zWAPFJAyct2FDBDiIIjPfZKr8Pl6hRLdHJ/0=,tag:eRfDX/AAEydPZVerOlP6+Q==,type:comment]
    #ENC[AES256_GCM,data:rSVcZ/MWgjNZxpPUJe0M3kXQ98HlaUGhiu1Y00S2HWmYmGaYfmFkOIHC7Xql8i/6jlL+JtM5QSPCOImvL1kSXoC5evcgUg==,iv:QxBPojT85UXo0BVKkHLS42Tjp6Z9/I+ofnGx66rqeNI=,tag:lugh6vpPwzBPyP3r9kvIrw==,type:comment]
    #ENC[AES256_GCM,data:ayey9+KlM8ZySXXgb00D09AdFZ5j+igS2w/I9ZvA2BtCJEKq9FfO2wLXqAMRWgJwhx1uHTB/msdT3/HirzvfnOQ=,iv:O4pGxeNQGgkrzJoefBpAH/xHSIdvhbeEYFNkBQQn5nA=,tag:w9LDXg5i/AgmAA7iLTk4EA==,type:comment]
    B2_KEY_ID: ""
    B2_KEY: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBka2xIa1QrdGNDVWlOei95
            NmNNbzlkRjNVMmMzNHRxalQyNDJDV21wbG00CjJLSmQzZ2ZoVWpNeE54OVpvRUJq
            VVIvOXVIcUlNQ1NjWkNqQU9tYWFlbDAKLS0tIEZmNjFrZlk3TGxLRklyQm40Q3p2
            NXZTUkhiczhVaGViNjIxYzVTOFozWFUKt8lwzBviEoDvRcxSj5VDQdzR3ll6R87o
            tCFqS87ZAnIVO7sV9+Ir/nH5/kf+sBj6qQaCgfGN/0KTP01Wn5Nz1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l2td9xa5h64qq804f7xmqmus7v6hzqdycfay30e6heylesuws3sf0a4xc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T21:22:30Z"
    mac: ENC[AES256_GCM,data:v6cEXtIFPP6mlQhSKxLeJlCJY8sgCMceV6U+WIt/64123FH6Vun6tJWzh8blePkjVhrI3vD9hqnJSIsZ+0tvgwRg27+SBY/JC2Cq5duy0ifw5bYHw7yYOQ8l3u9KLOGaudma2vCgvXKJEmdvrA7TMD36rVtAShsew5aHHvlx8H8=,iv:rfCIWV13UeJr9Jd9T6rOOv4BLJs7gU9qo+AZCiawMUA=,tag:wDGE8YKbhn+ojGuHo7UI4g==,type:str]
    version: 3.13.1
